### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by bep** [comment]
You can start by accepting the CLA.

**Comment by bep** [comment]
Merged in c50c668

**Comment by bep** [comment]
@korzonek having "Block nesting too deep" for 3 levels seems off, even Linus Torvalds have 3 levels in his code.

**Comment by bep** [comment]
I'm gonna reopen this. I reverted the merge. In one end I think this is a great tool (I found several easy-to-fix issues with Hugo) -- but I'm a little bit afraid that "people" are going to take all the bullet points you present literally. And 20+ lines functions etc. may in many cases be perfectly fine. Hey, even the  Go  according to your algos.

**Comment by bep** [comment]
Lets revisit this when this project get more mature/traction.

**Comment by korzonek** [comment]
@bep please keep codebeat on a radar and maybe give a try  to codebeat in a month time :) 

We are moving forward. codebeat grows and becomes more and more mature. 

Your feedback together with a very similar message from a few other people was trigger for us to implement "grading" for each issue to present how important issue is... some issues are small and some are more important.

If there are any other things you would like to see in this type of tool, please share. Feedback is great help for us because it defines our priorities in backlog. Thank you!

**Comment by korzonek** [comment]
@bep we have just released a new set of features in codebeat.

- Support for pull requests. codebeat will analyse every pull request when you add a new project using Github, and will post a status to provide you seamlessly with information where it matters the most.
- Enhanced Slack notifications. You no longer will have to switch context to see how your project or pull requests are performing in codebeat.
- Functionality to customise metrics and individual issues
- Detection of code smell - too many instance variables
- Experimental support for Obj-C. It requires calibration, but it works :)
- Support for Java and Kotlin. We want to help Android developers.
- We also calibrated support for Swift.

It would be super if you could give a try to codebeat :)

Keep on coding! 

#CleanCodeMatters

**Pull request closed without merging**
