### PR TITLE
Add '+' as one of the valid characters in urls specified in the front matter

### PR DESCRIPTION
**Pull request by egonSchiele**
The UnicodeSanitize function contains a list of valid characters, `+` should be one of those chars.

### CODE REVIEW

**Comment by bep** [comment]
Why should it be one of the valid characters?

**Comment by egonSchiele** [comment]
It is one of the characters that is valid in urls http://stackoverflow.com/a/1547940

**Comment by bep** [comment]
Hugo have its own restrictions. Thanks for your report.

**Comment by spf13** [comment]
@egonSchiele Not all of the characters in that list are acceptable in commonly used filesystems. Hugo will only permit characters that are both acceptable in all filesystems and valid URL characters. Additionally we avoid characters that may be filesystem acceptable but will interfere with programs (finder, explorer, ls, dir, etc) which are more particular. 

We did end up adding the "%" character even though it's an issue on windows due to its extensive use in URLs.

Is there a similarly valid use case for allowing the "+"?

**Comment by egonSchiele** [comment]
I don't know, @spf13 . To be honest, this is not an issue for me...I was merely trying to help by fixing issue #1290. Since it was marked `status/please contribute`, I assumed y'all did want this change and were merely looking for a PR.

**Comment by spf13** [comment]
Aah.. Thanks for providing the background. We appreciate the fix. I did some diligence and I can't find a reason to prohibit this character. It's fine on linux, mac and windows.. even back to Win95. 

I'm fine with merging unless @bep has a reason against it.

**Comment by bep** [comment]
No reason, please merge.

**Comment by spf13** [comment]
merged as c42982f

Thanks @egonSchiele. Sorry this one took a while to merge in. Looking forward to further contributions.

**Comment by egonSchiele** [comment]
Happy to help @spf13 !

**Pull request closed without merging**
