### PR TITLE
docs: Document Go's new `block` keyword. Fixes #1947

### LINKED ISSUE #1947: docs: Add doc for Go 1.6 block syntax
See https://github.com/spf13/hugo/pull/1836

### PR DESCRIPTION
**Pull request by ebsen**
This pull request would create a new page in [the Templates section of Hugo's documentation](http://gohugo.io/templates/overview/) that explains how blocks in Go 1.6 can work in Hugo. Initially, I just started a new section in the Go Template Primer but I felt the code examples made a blocks section long enough to warrant its own page.

I did not yet add this page to the navigation. Personally, I would think it fits well between [Content Views](http://gohugo.io/templates/views/) and [Partial Templates](http://gohugo.io/templates/partials/) but I wanted a team member's feedback before I just threw it in. 

Happy to change or resubmit as necessary. This is my first substantial pull request into a real project so do let me know if I missed anything.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
LGTM :+1: . I don't think the first commit was intended to be part of this pull request.

**Comment by bep** [comment]
Please one named Git branch per pull request. That is a good rule to live by.

**Comment by digitalcraftsman** [comment]
> Please one named Git branch per pull request. That is a good rule to live by.

That would indeed save us so time.

@bep beside that do you have something to add? Otherwise I would merge it.

**Comment by ebsen** [comment]
Yes, I'm sorry. I realized too late why rebasing matters. :(

**Comment by ebsen** [comment]
If it helps, I could resubmit as a new (single commit) pull request. That would allow me to add the page to the navigation too.

**Comment by digitalcraftsman** [comment]
You don't have to resubmit your additions in another pull request. 

> That would allow me to add the page to the navigation too.

Why shouldn't this be possible right know? The menu link would be `/templates/block/`. Take a look at the frontmatter of the pages where you add some paragraphs.

```yaml
menu:
  main:
    parent: content
next: 
prev: 
```

Add this to the frontmatter of `block.md` and add the links to the `prev` and `next` post. Don't forget to update the links in the previous and next page's frontmatter respectively.

**Comment by digitalcraftsman** [comment]
I added the necessary information for the menu and merged your commit as 65f9427031ae57c0d78360dbbfe03428fe922b49.

**Comment by ebsen** [comment]
@digitalcraftsman Thank you for fixing that for me. I see you grabbed the whitespace too. I meant to submit that as a separate request and didn't realize that commit made it into this one. I'll get my head wrapped around these so I don't make more work for maintainers in the future.

**Pull request closed without merging**
