### PR TITLE
add configuration variable: "disablePathToLower" See #557 

### PR DESCRIPTION
**Pull request by coderzh**
add configuration variable: "PathToLower" to specify whether to downcase the path/url. See #557

### CODE REVIEW

**Comment by bep** [comment]
There are some tests failures. Could you check up on that?

**Comment by coderzh** [comment]
All tests passed now.

**Comment by coderzh** [comment]
close it, I make another pull request with one commit.

**Comment by coderzh** [comment]
new pull request: https://github.com/spf13/hugo/pull/1392

**Pull request closed without merging**
