### PR TITLE
Wish a feature for TODO lists (Incorporate shurcooL/github_flavored_markdown?)

### PR DESCRIPTION
**Pull request by phtan**
This pull request addresses #2022

### CODE REVIEW

**Comment by bep** [comment]
This shouldn't  its own markup type. I'll create some more clear issues.

**Comment by phtan** [comment]
So... there will be new PRs to address the new issues #2269 and #2270 

Should I close this pull request, or will you do it yourself?

**Comment by bep** [comment]
>Should I close this pull request, or will you do it yourself? 

Do as you please. You may change this PR to fix one of them. #2269 is the priority as that is the top used markdown.

**Comment by shurcooL** [comment]
I agree that simply adding support for task lists into the existing Markdown mode (or both of them) is better than adding a 3rd new mode that users have to opt into. 👍

Basically apply a change like https://github.com/shurcooL/github_flavored_markdown/commit/2b74a5b054c18cbdf8589529327a7f9feba8b205 to the existing renderers you have.

**Pull request closed without merging**
