### PR TITLE
source: Consolidate filepath.Split calls

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by bep** [comment]
This looks fine; can you get the commit message in line with the guidelines.

**Comment by moorereason** [comment]
Please update your commit subject to match this PR title.  Then lgtm

**Comment by srinivasreddy** [comment]
@moorereason  Thanks

**Comment by bep** [comment]
>@moorereason Thanks. Done.

Doesn't look look done to me.

**Comment by moorereason** [comment]
:smile: `s/Source/source/`

**Comment by srinivasreddy** [comment]
@moorereason  Done. Thanks :smile:

**Comment by bep** [comment]
Merged in 21054f7

**Pull request closed without merging**
