### PR TITLE
all: remove dead code

### PR DESCRIPTION
**Pull request by bogem**

### CODE REVIEW

**Comment by bogem** [comment]
Don't hesitate to ask some questions or say something, if you want to :)

**Comment by bep** [comment]
A general comment would be that we are in a freeze period waiting for the Hugo 0.17 release. I know we have improvements to be had in the release speed department, but that is another story.

**Comment by bogem** [comment]
Done

**Comment by bogem** [comment]
Should I fix something more?

**Comment by bep** [comment]
Merged -- but notice my slightly modified commit message for future reference. Thanks for your contribution.

**Comment by bogem** [comment]
Ok, I will keep it in mind

**Pull request merged**
