### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by digitalcraftsman**
See #1611

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
I've also added a note about the `--renderToDisk` command that was mentioned by @moorereason. Correct me if I was wrong about the command in the release notes!

**Comment by moorereason** [comment]
I'd like to see the actual shortcode names in the release notes:
```md
* Hugo is now shipped with new built-in shortcodes: [1576](https://github.com/spf13/hugo/issues/1576)
  * `youtube` for YouTube videos
  * `vimeo` for Vimeo videos
  * `gist` for GitHub gists
  * `tweet` for Twitter Tweets
  * `speakerdeck` for Speakerdeck slides
```

**Comment by digitalcraftsman** [comment]
Done.

**Comment by bep** [comment]
Merged.

**Pull request closed without merging**
