### PR TITLE
all: Some performance and stability improvements

### PR DESCRIPTION
**Pull request by bogem**

### CODE REVIEW

**Comment by bep** [comment]
I see at least one bug introduced in this PR, so I'm not merging. I could point exactly what the problem is, but that may get a false sense of "completeness". But in general: Do not mix obvious refactoring improvements with changes you don't really understand what leads to.

**Comment by bogem** [comment]
But anyway please tell me, where is it🙏

**Comment by bep** [comment]
It is in the path fix(es).

**Comment by bogem** [comment]
Ok, thank you. Sorry for wasting your time!

**Comment by bep** [comment]
>Sorry for wasting your time!

You're not. The fixes you are contributing are valuable -- hope you soon start with some features/other functional bug fixes.

**Comment by bogem** [comment]
Thank you😊
Ok, and uf I fix that, will you merge it? Because I find the getting rid of redundant viper accesses is really good improvement

**Comment by bogem** [comment]
If it doesn't really produce any bugs

**Comment by bep** [comment]
remove the path commit

**Comment by bogem** [comment]
👌

**Pull request closed without merging**
