### PR TITLE
Add configuration option 'Title404'

### PR DESCRIPTION
**Pull request by halostatue**
Allow 'Title404' to be set for the title of the 404 page in config.*.

### CODE REVIEW

**Comment by bep** [comment]
Currently you can do

```
{{ $.Scratch.Set "title" "You are in a maze of passages, all alike." }}
{{ partial "header.html" . }}
```

It still feel hackish, but it's better than nothing. I do not believe that this PR is ever gonna get merged in its current form; so maybe best to close it?

**Comment by halostatue** [comment]
Let me see if the `{{ .Scratch… }}` solution works for me. If it does, I’ll close this because I have an alternative solution. If not, I would like to leave it open because I consider the fact that the 404 title is statically set to be a bug for which this is a (poor, but working) solution.

**Comment by bep** [comment]
Second thought, leave it open. I agree that it's a bug.

**Comment by bep** [comment]
Replaced by https://github.com/spf13/hugo/issues/1298

**Comment by halostatue** [comment]
I have been doing some work to make this enabled in my template anyway.

**Pull request closed without merging**
