### PR TITLE
Updated tutorial about Wercker

### PR DESCRIPTION
**Pull request by SamuelDebruyn**
Wercker updated its interface and infrastructure since this guide was written.
I've updated this guide to fit the current Wercker app.

* Default infrastructure is now docker
* Interface is now flat UI everywhere
* Wercker now has a registry to search for steps

### CODE REVIEW

**Comment by bep** [comment]
@ArjenSchwarz -- do these changes make sense? (Wercker is not my area of expertise)

**Comment by ArjenSchwarz** [comment]
A quick look seems to be great. I'll have a better look in a few hours when I can pull it down and see it as a page. As I was planning to do an update this weekend it's great to see this though. Thanks @SamuelDebruyn

**Comment by ArjenSchwarz** [comment]
@bep having had a closer look, this all looks good to me and can be merged.

**Comment by bep** [comment]
Merged and live soon.

Thanks @SamuelDebruyn and @ArjenSchwarz ...

**Comment by SamuelDebruyn** [comment]
No problem :) I'm working on some new Wercker steps to automatically check for dead links and minify the generated code.

**Pull request closed without merging**
