### PR TITLE
tplimpl: Add built-in print funcs to FuncMap

### PR DESCRIPTION
**Pull request by moorereason**
Add print, printf, and println to the Hugo FuncMap so that they are
accessible to the apply template func.

Updates #3139

### CODE REVIEW

**Comment by moorereason** [comment]
I didn't include any other built-in funcs because I don't know how relevant they are to the `apply` use case.  These print funcs may be enough to close the parent issue.

**Comment by digitalcraftsman** [comment]
`printf` is already part of the template funcs.

**Comment by moorereason** [comment]
I think you're missing point of this PR.

**Comment by digitalcraftsman** [comment]
I should have dug deeper. Bjørn already stated the problem: 

> Yes. apply looks in the Hugo internal map for existing funcs (printf is a built-in)... which is limiting. But nothing I can do without fixing Hugo. Can you create an issue on GitHub?

Just forget what I wrote.

**Pull request merged**
