### PR TITLE
tpl: Add template function 'asciidocify'

### PR DESCRIPTION
**Pull request by lafisrap**
I added 'asciidocify' function according to the 'markdownify' function. Also added a test.

`go build` and `go test ./...` show no errors.

### CODE REVIEW

**Comment by lafisrap** [comment]
I checked the AppVeyor Errors, but don't understand. I'd need help there, I guess.

Wercker doesn't show an Error log.

**Comment by moorereason** [comment]
https://ci.appveyor.com/project/spf13/hugo/build/1.0.3652#L786

```
=== RUN   TestFuncsInTemplate
ERROR: 2016/08/27 09:17:10 content.go:468: asciidoctor / asciidoc not found in $PATH: Please install.
                  Leaving AsciiDoc content unrendered.
--- FAIL: TestFuncsInTemplate (0.02s)
	template_funcs_test.go:245: Diff:
		["asciidocify: **BatMan**" "<p><strong>BatMan</strong></p>" "</div>" "asciidocify: <div class=\"paragraph\">"]
```

**Comment by lafisrap** [comment]
Ok. Then its not a problem of the new code, but that the asciidoc functionality needs asciidoctor installed on the test system (gem install asciidoctor). Where are the tests running?

**Comment by bep** [comment]
@lafisrap the solution would be to conditionally run the test if assciidoctor is installed (see `helpers.HasAsciidoc` or something). But that is not the main problem with this PR. Having asciidoc running once per content page is slow enough, but having it available as a template func may be pushing it, with one hardware thread per func invocation.

**Comment by bep** [comment]
I will close this now. We might revisit this in the future when we get native Asciidoc support.

**Pull request closed without merging**
