### PR TITLE
Allow page.HasMenuCurrent() and node.HasMenuCurrent() to proceed with…

### PR DESCRIPTION
**Pull request by vjeantet**
… multi-level nested menus

Currently HasMenuCurrent() only process the first 2 levels.

### CODE REVIEW

**Comment by bep** [comment]
There is a breaking test. The code looks correct to me, but the tests should be adapted/expanded.

**Comment by vjeantet** [comment]
wow.. :( i'll try to look around theses broken tests

**Comment by bep** [comment]
@vjeantet as I wrote those tests, I may be of help i needed :-)

**Comment by vjeantet** [comment]
no problem @bep, be my guest :)

**Comment by vjeantet** [comment]
i will try to work on theses test tonight

**Pull request closed without merging**
