### PR TITLE
Wercker automated deployment tutorial update

### PR DESCRIPTION
**Pull request by keanemind**
The current tutorial on using Wercker for automated deployment is very old and out of date. I have updated it to reflect the current Wercker website. This includes some new and updated screenshot images. Let me know if anything needs to be changed.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @keanemind,

thank you for submitting an update for this tutorial. Is this still a work in progress?

**Comment by keanemind** [comment]
Hi, it's complete. I forgot to add the important step of giving Wercker a theme when I first made the pull request. In the future, when I have more time, I think I will go back and improve a lot of the tutorial's grammar and writing style. However, I don't plan on doing that in the next week.

**Comment by digitalcraftsman** [comment]
Merged as 396276aa.

**Comment by keanemind** [comment]
@digitalcraftsman The website still says "Last revision: January 12, 2015" at the bottom of the page, even though I edited "lastmod" in the tutorial's front matter. Is this a bug? Jan 12 is the date of "date" in the front matter.

**Comment by moorereason** [comment]
@keanemind,
`Failed to parse lastmod '2017-2-26' in page tutorials/automated-deployments.md`

**Comment by keanemind** [comment]
Whoops, should have been '2017-02-26'. I should have looked at the outputs of the CI checks even though they passed. I suppose I'll make a new pull request to fix that.

**Pull request closed without merging**
