### PR TITLE
Add Camunda blog and docs showcases

### PR DESCRIPTION
**Pull request by zeropaper**
We :heart: Hugo at Camunda.

### CODE REVIEW

**Comment by anthonyfok** [comment]
Thank you for your contribution, @zeropaper!

But before I merge, may I ask you a favour?  Could you please recapture the thumbnail images, but this time, save them as PNG files instead?  I think these thumbnails would look much better as PNG files, and the file size would be about the same or even less because your website contains only a handful discreet colours, i.e. no gradients or photos.  :-)

Many thanks!

**Comment by zeropaper** [comment]
Hi @anthonyfok
Sure!
The new pictures (and their respective paths in md) have been update.

Cheers and greetings from Berlin

**Comment by anthonyfok** [comment]
Thanks for the quick reply!

I optimized the PNG files, squashed the two commits together,
and merged the result as d7ef272 (master) and 79ad055 (v0.15.docs).

 And your websites are now live on the Hugo [Site Showcase](http://gohugo.io/showcase/) page!

**Comment by zeropaper** [comment]
Thanks a lot!

**Pull request closed without merging**
