### PR TITLE
Remove traces of the BaseURL from the sourceRelativeLinksEval code

### PR DESCRIPTION
**Pull request by SvenDowideit**
Closes: #2227

So I think this fixes it properly for most combinations of `canonifyURLs`, `relativeURLs` and `sourceRelativeLinksEval` and `baseurl`

but because the baseUrl part is added (er, i think) in a transform at the end, I have no idea how to write a test for it

### CODE REVIEW

**Comment by SvenDowideit** [comment]
reliable manual testing for a 4x4 matrix of options, and being sure that they're run every code change is why we're in this mess.

**Comment by SvenDowideit** [comment]
I intend to work on the `relativeURLs=false` results at some point - see https://github.com/spf13/hugo/issues/2227#issuecomment-232013252

**Comment by bep** [comment]
>I'm no longer using hugo though, so idk.

Are you now talking about you personally or Docker? If I remember correctly, @spf13 merged this to support a very Docker specific need, and if that is not the case anymore, we must consider removing this feature.

**Comment by SvenDowideit** [comment]
@bep - both are true. (I only worked on Hugo because Docker had made the choice to use it - and I don't work there anymore, and from what I can tell Docker now uses GitHub pages)

IMO, having hugo do linking in a way that is compatible with the way relative links work on Github pages is important to Hugo, and this code was implemented to achieve that. Its not a Docker specific thing, but that was certainly the reason I worked on it.

**Comment by bep** [comment]
>pages is important to Hugo

That may be true, but only if someone has the time to follow up on issues to make sure it actually works. This is not a pet of mine.

**Comment by SvenDowideit** [comment]
closing, as neither @bep, nor I want to maintain this feature.

**Pull request closed without merging**
