### PR TITLE
Feature: GetJson and GetCsv in short codes or other layout files.

### PR DESCRIPTION
**Pull request by SchumacherFM**
I have finished the integration of getJson and getCsv into hugo as far as I think it fits.

I'm not a hugo (and Go) expert of where to put these functions and correct naming of functions and vars.

I would be glad if you can comment on spotted errors, bugs, bad design, etc. or even help me to improve the code more.

All tests and the new tests are passing. Goimports has reordered some import paths.

I have written a blog post about that new feature: [http://cyrillschumacher.com/2014/12/21/dynamic-pages-with-gohugo.io/](http://cyrillschumacher.com/2014/12/21/dynamic-pages-with-gohugo.io/)

There is not yet any official documentation because I want to get the code right. I think once this feature is merged as a hidden feature into hugo and some people tested it in the wild with no given complaints I will write the docs.

Looking forward for a successful merge :-)

### CODE REVIEW

**Comment by bjornerik** [comment]
@spf13 I feel the API here is pretty set in stone (simple and clear). There may be stuff to improve on caching and documentation, but there are arguments to pull it in as a "silent feature" for a while ... to play with it and get a feeling.

**Comment by derekperkins** [comment]
:+1: Great idea!

**Comment by SchumacherFM** [comment]
I've added the option ignoreCache, fixed a bug when the cache folder didn't exists and also rebased my branch with the current commits from master.

**Comment by thomasmodeneis** [comment]
up !
sorry to disturb,
any project collaborators up to do this merge? o/
thank you

**Comment by thomasmodeneis** [comment]
I have it running with the fork github.com/SchumacherFM/hugo.

But the url I want to call is composed with prefix + id + sufix
The problem is that I can not make it work a way to concatenate vars with hugo:

{{ $id := .Params._id }}
{{ $url_pre :=  "http://localhost:3000/db/persons/" }}
{{ $url_post := "/limit/10/skip/0" }}
{{ $finalurl  := $url_pre + $id}}
 {{ $gistJ := getJson $finalurl }}
{{range first 5 $gistJ }}
<li><a href="#" target="_blank">{{.name}}</a></li>
{{end}}

Is there a way to concatenate vars to build this composed url ??
Thank you.

**Comment by bep** [comment]
printf - see a recent discussion in the forum.

**Comment by thomasmodeneis** [comment]
printf works just fine o/, thanks for the great tip :)

**Comment by SchumacherFM** [comment]
@thomasmodeneis I have changed the parameters for getJson and getCsv function so that this is now possible:

```
{{ $id := .Params._id }}
{{ $url_pre :=  "http://localhost:3000/db/persons/" }}
{{ $url_post := "/limit/10/skip/0" }}
{{ $gistJ := getJson $url_pre $id $url_post }}
```

and of course it is still possible to do `{{ $gistJ := getJson "http://myurl.com/content.json" }}`

@bep and @spf13 What is missing or wrong that I can correct that this feature will get merged within the next couple of days? 
I know something gone wrong with one of my rebase commands so I can send a new pull request.

Please advise.

**Comment by bep** [comment]
@SchumacherFM The PR looks fine to me (no need to send a new one) -- but for "major changes" like this, I like to wait for @spf13's approval before pulling in the code.

But I want/need this, too.

**Comment by thomasmodeneis** [comment]
@SchumacherFM Thank you, this is really useful.

I'm running the hugo binnary inside your blog (https://github.com/SchumacherFM/blog-cs/)  to make some test for this feature, but when I try the hugo on https://github.com/SchumacherFM/hugo at the compilation time I get into:
```
shortcodes/demoJsonGH.html:3: function "getJson" not defined
```
Have you commited  #748 to https://github.com/SchumacherFM/hugo or you are using other repo  ? 
Cheers.

**Comment by SchumacherFM** [comment]
@thomasmodeneis

My repo https://github.com/SchumacherFM/hugo is pulling in the sources from https://github.com/spf13/hugo. So when I develop I always work in https://github.com/spf13/hugo with such a git setup:

screen shot 2015-02-09 at 9 27 59 am

The git commands `git branches` and `git remotes` are aliases from https://github.com/mathiasbynens/dotfiles

Please pull the latest changes from my blog and checkout master.

Run it like this:

```
cys at cys in ~/Sites/blog-cs on master
$ go run ~/GoPro/src/github.com/spf13/hugo/main.go server -w -v --baseUrl="localhost" --cacheDir="./cache"
INFO: 2015/02/09 Using config file: /Users/cys/Sites/blog-cs/config.yaml
INFO: 2015/02/09 syncing from /Users/cys/Sites/blog-cs/static/ to /Users/cys/Sites/blog-cs/public/
INFO: 2015/02/09 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
0 draft content
0 future content
27 pages created
0 paginator pages created
41 tags created
3 categories created
in 520 ms
Watching for changes in /Users/cys/Sites/blog-cs/content
ERROR: 2015/02/09 Symbolic links not supported, skipping '/Users/cys/Sites/blog-cs/static/piwik'
Serving pages from /Users/cys/Sites/blog-cs/public
Web Server is available at http://localhost:1313/
Press ctrl+c to stop
```

**Comment by thomasmodeneis** [comment]
Thanks for your help @SchumacherFM, also for the dotfiles tip, this was really nice. 
I'm now able to compile no errors!
Cheers

**Comment by spf13** [comment]
@SchumacherFM @bep 

+1. Let's get this in before the v0.13 release

**Comment by spf13** [comment]
@SchumacherFM I love what you are doing with Hugo. You are taking it to places I never thought of. It's really awesome to see your innovative ideas coming through.

**Comment by bep** [comment]
@SchumacherFM I tried to merge this ... and the merge itself is easy ... but I tested it briefly, and could not get it to work.

I tried the Youtube example on your site. Had to find a "public" userid, but all I get is errors: 

```
 ERR: template: shortcodes/yt.html:6:12: executing "shortcodes/yt.html" at <$p.language>: can't evaluate field language in type string
```

I'm sure I *could* get it to work if I spent more time debugging this, but what I'm say is: You should write some documentation about how to use this. And for the exernal example, try to find a "stable resource" (i.e. a JSON that will stay there for some years to come).

**Comment by pcdummy** [comment]
I just uploaded [hugo-lightslider-example](https://github.com/pcdummy/hugo-lightslider-example), its a demo of Hugo with lightSlider and lightGallery.

I use the extended/modified version from Cyrill Schumacher, see [pull #748](https://github.com/spf13/hugo/pull/748).

I uploaded it [here](http://hugo-lightslider.pc-dummy.net/)

Thank you @spf13! A great piece of software you made, think i gonna use it a lot in the near future.

Also thanks to @SchumacherFM! I also love what you do with hugo.

**Comment by SchumacherFM** [comment]
@pcdummy Wow Cool Work! The branch `SchumacherFM_SourceJSON` contains a new feature (streamed virtual pages) which is WIP - work in progress - so please switch back to branch `dynamicPagesWithJsonCsv` which should get merged in here in the next days.

**Comment by pcdummy** [comment]
Did so, thanks @SchumacherFM.

**Comment by SchumacherFM** [comment]
@bep I have written a warning in my blog post regarding the youtube API v2 JSON stream which makes hugo panicing because some keys contain `$` signs and I don't know how to access special written keys in html/template. When you switch to the YT API v3 version then everything should be fine.

You should try the getJson feature with https://github.com/SchumacherFM/blog-cs/blob/master/layouts/shortcodes/ghStarred.html short code:

```
{{< ghStarred url="https://api.github.com/user/394382/starred?page=1" >}}
```

These are your starred repos ;-)

**Comment by SchumacherFM** [comment]
I will start on the week with writing the docs on a new branch.

**Comment by bep** [comment]
@SchumacherFM I copied the sample from your blog post - it did not panic, it just returned a slice of strings. I'm not merging code that doesn't pass the first smoke test.

**Comment by spf13** [comment]
@SchumacherFM, I think this is a great feature and we would love to have it in hugo. It's also a big feature and one that I think a lot of people will want to use, so we definitely need good docs to avoid massive questions on the forum about it. Thanks for your willingness to participate and help.

**Comment by SchumacherFM** [comment]
I've just started writing and ... how should I name the new page in the docs?

> Dynamic Content

Is my current favourite but not really a nice one. Has someone a better idea = name?

**Comment by thomasmodeneis** [comment]
Dynamic Pages is how they call it on Middleman.

**Comment by spf13** [comment]
I like dynamic content

**Comment by SchumacherFM** [comment]
Documentation has been added!

https://github.com/SchumacherFM/hugo/commit/4cd023c0e43eeb8ddf96a36bb196a1df95eea367

Please report any weird stuff and also if it is ok to include future features (people will get more excited about hugo :yum: )

**Comment by bep** [comment]
The documentation should be about the current feature-set. Nobody knows what the future brings.

**Comment by SchumacherFM** [comment]
Moved it to another branch. Anything else ok?

**Comment by spf13** [comment]
I've merged this in. Excellent contribution @SchumacherFM. Looking forward to more.

**Comment by SchumacherFM** [comment]
cheering_minions

Awesome! More stuff is coming.

**Pull request closed without merging**
