### PR TITLE
Docs: improve shortcodes page

### PR DESCRIPTION
**Pull request by digitalcraftsman**
See #1613

### CODE REVIEW

**Comment by spf13** [comment]
Is this still a WIP? Are you ready for us to merge/review it?

**Comment by digitalcraftsman** [comment]
I've asked the same question in the corresponding issue #1613. @moorereason gave me feedback during the PR was in made. In my eyes everyhing should be fine as long as nobody has something to complain.

**Comment by moorereason** [comment]
LGTM

**Comment by anthonyfok** [comment]
Thank you all!

Merged as 2e3d5c2 (master) and edc8e82 (v0.15.docs)

**Pull request closed without merging**
