### PR TITLE
Unexport mainSite and hugoCmd; create a very simple API

### PR DESCRIPTION
**Pull request by hacdias**
@bep I don't know if this API (if it can be called that way) is a better way to use Hugo. If so, it can be improved in the future to add more functionalities.

### CODE REVIEW

**Comment by hacdias** [comment]
I'm not understanding why this is failing [here](https://travis-ci.org/spf13/hugo/jobs/109166956#L181).

**Comment by bep** [comment]
Try to rebase against master.

**Comment by hacdias** [comment]
Still same error. But that works!!! Affs.

**Comment by hacdias** [comment]
Moved to #1860

**Pull request closed without merging**
