### PR TITLE
add Algolia as commercial search service

### PR DESCRIPTION
**Pull request by anagio**

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @anagio,

please accept the contribtor license agreement in the comment below as last step.

**Comment by anagio** [comment]
@digitalcraftsman not sure why but after authenticating and attempting to sign the CLA it is not working.

**Comment by digitalcraftsman** [comment]
And the comment of the cla assistant explains why:

> Peter Panagiotakos seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

GitHub identifies users based on their email address'. You commit seems to use a email address that is unknown to Github (and therefore to the cla assistant). You've to add the email from the commit to your account so that your identity can be veryfied.

**Comment by anagio** [comment]
@digitalcraftsman thanks

**Comment by digitalcraftsman** [comment]
I merged your additions as 198efc89ca537a859f93cd775ea221d5032f1ac8 (master) and 86bda2e5bd11de280fb0d35a0696963e3516f46c(v0.16.docs).

Best regards,
Digitalcraftsman

**Pull request closed without merging**
