### PR TITLE
Add ReadDir function to list local files

### PR DESCRIPTION
**Pull request by rustyoz**
Adds functionality wanted by @Lynxiayel in this community [post](http://discuss.gohugo.io/t/a-way-to-traverse-local-files/1249)

### CODE REVIEW

**Comment by spf13** [comment]
Can you add a test for this?

**Comment by rustyoz** [comment]
I honestly don't know how I would do that pragmatically. 
The addition to the docs includes a shortcode that is used in the documentation that uses the command. The command is passed a string with a forward slash included and this works fine on Windows. 

At the moment all I can do is say that it has worked for me on both windows and linux with forward and backward slashes used in the path.

**Comment by bep** [comment]
@rustyoz: This looks fine, but as it is now it is possible to navigate outside the WorkDir. This may sound innocent, and it mostly is, but one could imagine a theme author doing something stupid.

So some thightening of that issue would be nice.

**Comment by rustyoz** [comment]
I have updated the commit to include a test for parent directory markers ".." which should prevent navigation outside of the working directory

**Comment by rustyoz** [comment]
@spf13 @bep I would fix the merge error but I don't know what is causing it. any ideas?

**Comment by bep** [comment]
@rustyoz I haven't forgotten this. I want this feature. Just want some other to chime on to evaluate if the ".." check is protection good enough.

@spf13

others?

**Comment by rustyoz** [comment]
All good. It seems like the appveyor test failure was due to a missing newline of all things.

**Comment by bep** [comment]
Merged in 81e69c4

This is very useful. And thanks for taking the time to write some solid documentation. It's boring, but needed.

**Pull request closed without merging**
