### PR TITLE
Correct spelling for "parameters"

### PR DESCRIPTION
**Pull request by vsopvsop**

### CODE REVIEW

**Comment by vsopvsop** [comment]
I don't want to sign CLA. Shall I close this PR?

**Comment by moorereason** [comment]
@vsopvsop, if you don't agree to the CLA, we can't accept your contribution.  If that's the case, close this PR.

**Comment by digitalcraftsman** [comment]
If you don't want to accept the CLA we could we could fix this typo ourselves. The issue itself is trivial.

**Comment by vsopvsop** [comment]
Accepted the CLA.

**Comment by digitalcraftsman** [comment]
And thanks for the fix. I've merged your commit as 7cb8107735d8612a26ad95dfdec2141b0e0e6baa.

**Pull request closed without merging**
