### PR TITLE
added surge to hosting providers

### PR DESCRIPTION
**Pull request by robmuh**
Minimal change to list of hosting providers on the home page. I am not affiliated with [Surge.sh](//surges.sh) in any way but find them one of the easiest hosting providers to teach to students.

### CODE REVIEW

**Comment by bep** [comment]
Can you fix the commit message (see contribution guidelines).

**Comment by robmuh** [comment]
Please let me know if that `--amend` took to your liking.

**Comment by robmuh** [comment]
I am sorry. I just realized I deleted the Aerobatic provider. Adding it back. Ugh. It's early.

**Comment by anthonyfok** [comment]
For reference, this pull request was closed and reopened as #1996 by Rob.

**Pull request closed without merging**
