### PR TITLE
Fix Dockerfile

### PR DESCRIPTION
**Pull request by gilbsgilbs**
Hi,

The Dockerfile was not working anymore because of some tests failing (??). I simplified it, removed unecessary layers, added missing dependencies in "prefetch" layer and it started working magically.

Let me know if I missed some use cases in comparison to the previous version.

### CODE REVIEW

**Comment by bep** [comment]
>Let me know if I missed some use cases in comparison to the previous version.

Looks good, but could you hit the "sign CLA" button.

**Comment by gilbsgilbs** [comment]
@bep Had to push again into my branch to make CLA realize I signed the agreement.  Should be fine now.

**Comment by bep** [comment]
>@bep Had to push again into my branch to make CLA realize I signed the agreement. Should be fine now.

It still says "not signed"; it may be a diff between your commit email and your GitHub email -- you can register multiple email addresses in your GH profile.

**Comment by gilbsgilbs** [comment]
@bep That's actually what I did, but it didn't change anything. As a consequence, I pushed again into my branch (to trigger the check manually). Not sure why it says "not signed yet", but notice that the CLA check has completed successfully on the summary. If you will, I can close this PR and re-open it to trigger the checks again. 100% sure it will be okay then.

Thanks.

**Comment by bep** [comment]
>@bep That's actually what I did, 

Ah, sorry -- I see that now. Thanks!

**Pull request merged**
