### PR TITLE
docs: Regenerate commands docs

### PR DESCRIPTION
**Pull request by bogem**
See https://github.com/spf13/hugo/pull/3399#issuecomment-297527784

### CODE REVIEW

**Comment by bogem** [comment]
Stop. I will regenerate all docs now.
https://github.com/spf13/hugo/commit/656f818867ab3e3dd9a9cc067e6da2e54bd6548b chages just case of flags' usage, but help is another now (e.g. disableKinds flag appeared)

**Comment by bogem** [comment]
Okay, it's bug in cobra/doc, what it doesn't add help flag

**Comment by bogem** [comment]
@bep I think we can merge it before v0.21 release

**Comment by bep** [comment]
No, this will have to wait. it's not important enough.

**Comment by bogem** [comment]
Okay

**Pull request closed without merging**
