### PR TITLE
Add blog of Enrique Saez Gil, https://esaezgil.com to the site showcase

### PR DESCRIPTION
**Pull request by esaezgil**
Add blog of Enrique Saez Gil, https://esaezgil.com to the site showcase

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @esaezgil,

thank you for adding your website to the showcase of Hugo. I've merged your contribution as  a037b855. Hugo's showcase section should be updated within the next minutes.

Cheers,
Digitalcraftsman

/cc @rdwatters

**Comment by rdwatters** [comment]
Thanks @digitalcraftsman 

@esaezgil FYI, it's up on the future docs site as well:

https://hugodocs.info/showcase/

**Comment by bogem** [comment]
@rdwatters [hugodocs.info](https://hugodocs.info) are so excellent 😍

**Comment by esaezgil** [comment]
thanks all! new docs look great :)

**Pull request closed without merging**
