### PR TITLE
Make livereload depend less on presence of body tag

### PR DESCRIPTION
**Pull request by vyuh**
Add livereload script before the first matching `endTag` among the following:
- `</body>`
- `</BODY>`
- `</html>`
- `</HTML>`
  If all above attempts fail to inject livereload, then append livereload to end of document if it starts with `<!DOCTYPE html>`.

This makes livereload work for HTML pages that omit optional tags including `body`
- Earlier, livereload only worked on webpages generated from layouts that have a body closing tag.
- There was no way to achieve this new behaviour using present command line flags.
- This behaviour is desired by all people who wish to omit optional HTML tags, including `body`, in layouts. See, https://google.github.io/styleguide/htmlcssguide.xml#Optional_Tags
- It is harmless to inject the livereload script at the end of content as a last resort when all attempts to replace patterns (like `</body>`) fail.
- Anyone who wants to avoid this new behaviour (why?) can use `--disableLiveReload` with `hugo server`.

See #1526

### CODE REVIEW

**Comment by bep** [comment]
>It is harmless to inject the livereload script at the end of content as a last resort when all attempts to replace patterns 

This assumes, of course, that all content is HTML.

**Comment by vyuh** [comment]
@bep if some other kind of content is generated, and its proper function depends on non injection of `livereload.js`  based on  absence of body tag, then I agree that I have not considered that case.

**Comment by bep** [comment]
The non HTML content is rare currently, but I have a site that produces a JSON file that would be messed up by this PR.

Footnote remark: Your replacement logic is also slightly flawed: It seems to add an end body tag and it is more effective to use append instead of bytes.Join.

**Comment by vyuh** [comment]
Thank you for pointing out flaws. I have improved the code.
Now, it:
    - Does not end body tag when it was not there in first place
    - uses `append` instead of `bytes.Join`

This is the first time I am writing something in Go. I did
look up for something like `bytes.Append` but there wasn't
one, so I had settled for first thing I found, that did the job.

**Comment by vyuh** [comment]
I searched the master branch for usages (direct and indirect) of 
`LiveReloadInject`.

This is the rough tree:
- `LiveReloadInject` in `transform/livereloadinject.go`
    - `renderAndWritePage` in `hugolib/site.go`
        - `pageRenderer` in `hugolib/site.go`
        - `taxonomyRenderer` in `hugolib/site.go`
        - `renderListOfTaxonomyTerms` in `hugolib/site.go`
        - `renderSectionLists` in `hugolib/site.go`
        - `renderHomePage` in `hugolib/site.go`

For this pull request to work, it is necessary that `hugo` calls these
functions only to generate content that is HTML.

To support other content types, it is sensible to provide a 
page specific `nolivereload` variable.

**Comment by bep** [comment]
We have had this discussion before, and my argument is this:

If you want livereload and do not have a body in your HTML template: Add a body tag to your HTML template.

**Comment by vyuh** [comment]
For users who omit optional tags, adding a body close tag is a workaround,
not a solution. They have no proper way to get `livereload` feature. Having
to change layouts to something inconsistent with their style of authoring
HTML is disheartening.  More so, because this is easily avoidable.

The requirement that injector function must allow non HTML content to pass
through cleanly, is an unclear design restriction considering that:

- The injector function is called only in situations where an HTML page is
  being generated.
- Injection of `livereload` script makes sense only for HTML content.
  No other kind of content requires to pass through this.
- Support for correct generation of other formats, can be added by creating
  clear and distinct interfaces. For example, by adding a `renderAndWriteJSON`
  function for handling JSON. See `renderAndWriteXML` which does not pass
  content through `livereload` injector.

**Comment by vyuh** [comment]
For now, I have added a check to ensure that `livereload` is injected only to
documents beginning with "<!DOCTYPE html>". I would have started with a more
inclusive check, but using `regexp` might slow down the service of html pages
too much. This is the most unintrusive way that I could think of, to resolve
this.

Still, if this fallback behaviour conflicts with other goals of `hugo`
project, please consider adding a command line flag like `--forceLiveReload`
for this use case. Usability of `livereload` feature should not depend on
how one authors HTML in layout files.

**Comment by bep** [comment]
I'm closing this. This works fine as is, and making it more complex will introduce other problems, for non HTML files etc. Thanks for your contribution.

**Pull request closed without merging**
