### PR TITLE
Add yushuangqi.com to the showcase

### PR DESCRIPTION
**Pull request by ysqi**

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @ysqi,

before merging your website to the showcase, please make sure that...

- your commit message contains `yushuangqi.com`, not `example.com`
- you accept the contributor license agreement above
- your screenshot has the dimensions of 600px by 400px

**Comment by ysqi** [comment]
@digitalcraftsman I fixed it.

**Comment by digitalcraftsman** [comment]
Could you please accept the contributor license agreement?

**Comment by ysqi** [comment]
of course!

**Comment by digitalcraftsman** [comment]
Maybe I should have noted that you need to click the yellow badge in the second comment.

**Comment by ysqi** [comment]
@digitalcraftsman  Done.

**Comment by digitalcraftsman** [comment]
I've merged your contribution as 0698f294c6d335031951f1cb528c90f2a120eebb (master) and 56300637cc8ab7f259469007afd9ef1562707bb2 (v0.15.docs).

The website should be updated within the next minutes.

Cheers,
Digitalcraftsman

**Pull request closed without merging**
