### PR TITLE
Allow to access the rest of content after summary

### PR DESCRIPTION
**Pull request by opennota**
A quick and dirty PR for #716

### CODE REVIEW

**Comment by spf13** [comment]
@opennota 

I hate to ask this, but HEAD has drifted quite a bit since this PR. Now that v0.13 has shipped I'd love to merge this in. Would you be able to bring it up to date and repush?

**Comment by anthonyfok** [comment]
Hi @opennota, would you like to follow up on what @spf13?  Because hugolib/page.go has seen some changes since you made your original Pull Request, it cannot yet be merged directly and need a little more work on your part.  Could you please do that so that @spf13 can merge it for v0.14?

Many thanks!

**Comment by bep** [comment]
@opennota I think many would want this. Would be nice if you could revisit this.

**Comment by opennota** [comment]
Rebased.

**Comment by bep** [comment]
Great.

A couple of comments.

1) The above only supports "manually summaries". Users mix and match these and would expect to use the same template constructs for both.
2) There is still some "double work"  going on in here. Some of it may be out of scope of this PR (I would assume that, in most cases, one would use either `Content` or `ContentAfterSummary` and not both, so `Content` and `TableOfContents` could be methods that could be lazily evaulated) -- I would assume that  `ContentAfterSummary` is called several times, so cache the result, and assume that it will called from multiple go-routines at once. But I have not thought this all through, there may be better ways.

**Comment by spf13** [comment]
CLA not signed. Closing.

**Pull request closed without merging**
