### PR TITLE
Replace *bytes.Buffer with io.Writer in rendering

### PR DESCRIPTION
**Pull request by mvdan**
Found via github.com/mvdan/interfacer.

### CODE REVIEW

**Comment by bep** [comment]
Merged in 7c5a1fd ... and thanks for the quality commit message.

**Comment by mvdan** [comment]
Sarcasm? :)

**Comment by bep** [comment]
No. I have fought pretty hard to get people, esp. @spf13, in line with our simple commit message guidelines ... Yours may be short (which in this case is good), but spot on correct.

**Comment by mvdan** [comment]
Oh, hadn't noticed the commit message guidelines. Saw the usual fmt, rebase and test and assumed it was as usual.

My personal commit message policy is very similar to yours, so thankfully we're on the same page. Although I try to keep the bodies short whenever possible, unless they really must explain something.

**Pull request closed without merging**
