### PR TITLE
Allowing to pick a specific file out of a gist.

### PR DESCRIPTION
**Pull request by sprig**
This change would allow one to pick a specific file to embed out of a multifile gist.

### CODE REVIEW

**Comment by moorereason** [comment]
Please update `docs/content/extras/shortcodes.md`

**Comment by sprig** [comment]
done.

**Comment by moorereason** [comment]
lgtm

**Comment by bep** [comment]
Looks good to me, too. Could you squash the 3 commits into one?

**Comment by sprig** [comment]
Done.

**Comment by bep** [comment]
Could you also fix the commit message (see guidelines).

**Comment by sprig** [comment]
I hope this is better?

**Comment by bep** [comment]
"better" is subjective, but it is correct.

**Comment by bep** [comment]
Merged in e9008b9 thanks for the contrib.

**Comment by sprig** [comment]
Thanks for the patience! Sorry I missed the guidelines...

**Pull request closed without merging**
