### PR TITLE
Remove trailing \n in toml front matter

### PR DESCRIPTION
**Pull request by cyrilRomain**

### CODE REVIEW

**Comment by cyrilRomain** [comment]
FYI, I do accept CLA, not the assistant to access my account. 
I'm a GitHub user, just commited with my public email.
Feel free to cherry pick.

**Comment by digitalcraftsman** [comment]
@bep wouldn't users add a new line content anyways?

**Comment by bep** [comment]
@digitalcraftsman Yes, I think we can close this one. It looks like a preceding newline to me, but that doesn1t matter. @cyrilRomain thanks for the contribution, but I think we'll stick with what we got.

**Comment by cyrilRomain** [comment]
The patch actually removes the trailing empty line inserted _inside_ the toml front matter, when the "hugo new" is called, i.e. right before the closing +++.
IHMA to be consistent with YAML front matter, that newline shoud be removed from toml front matter or added to yaml front matter.

**Pull request closed without merging**
