### PR TITLE
docs: Add sanjay-saxena.github.io to the showcase

### PR DESCRIPTION
**Pull request by sanjay-saxena**

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @sanjay-saxena,

thank you for adding your page to the showcase. In order to merge your pull request please make sure to sign the contributor license agreement that is linked in the comment above. You only have to do it once and it just takes a few clicks.

Cheers,
Digitalcraftsman

**Comment by sanjay-saxena** [comment]
Hi @digitalcraftsman,

I already did that at the time of submitting the pull-request. Note the following:

```
You have signed the CLA already but the status is still pending? Let us recheck it.
```

Thanks!

**Comment by digitalcraftsman** [comment]
Ok I see the issue. GitHub / the CLA assistant identity users based on their email address. You seem to have created a commit that isn't associated with you GitHub account. Hence the assistant is unable to identify you.

The easiest way to fix this is to add the email address you used in the commit for this PR to the settings.

**Comment by sanjay-saxena** [comment]
Hi @digitalcraftsman,

My github account `sanjay-saxena` has email set. Also, whenever this PR is being updated,  I am receiving emails in the same account. Can you please let me know how to fix this issue?

Thanks!

**Comment by sanjay-saxena** [comment]
I will re-issue a new PR with `user.email` property set to the same value as to what's specified in my Github account `sanjay-saxena`.

**Pull request closed without merging**
