### PR TITLE
Showcase addition

### PR DESCRIPTION
**Pull request by balaramadurai**

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @balaramadurai,

please make sure that the thumbnail has the required dimensions of 600px by 400px.

**Comment by balaramadurai** [comment]
Thanks @digitalcraftsman, I swapped the screenshot with another one.

Have fun!
Bala

**Comment by digitalcraftsman** [comment]
I've merged your contribution as 7b8a09d. The website should be updated within the next minutes.

Cheers,
Digitalcraftsman

**Comment by balaramadurai** [comment]
Thanks a lot, @digitalcraftsman 👍

**Pull request closed without merging**
