### PR TITLE
Add yulinling.net to showcase

### PR DESCRIPTION
**Pull request by Lynxiayel**
I added yulinling.net, my blog, to the showcase, the related source code (removing private info) is also included.
Plz review and merge, thanks.

### CODE REVIEW

**Comment by anthonyfok** [comment]
Hello @Lynxiayel,

Thank you for your contribution!

I needed to make the following modifications:

 * Remove leading `+` characters on each line of `docs/content/showcase/yulinling.net.md`
 * Correct the thumbnail filename listed in `yulinling.net.md` (png → jpg)
 * Add Chinese name "语林灵" to `yulinling.net.md`
 * Recapture and resize your thumbnail image to 600x400.

Also, it is preferable to create your pull request from a topic branch, not from `master`, as now you would need to use `git pull --rebase` or something similar to get your local `master` branch to match that of upstream.  :wink:

Merged as 68b8dd73de032318cd7617b024c0bd0a4e4dab2c (`master`) and 19a7aa9307d44484b74f12e35e90f5ffed77ab65 (`v0.14.docs`).

再次感谢！很高兴见到越来越多中文网站使用 Hugo。 :wink: 

Anthony

**Comment by Lynxiayel** [comment]
Oh thanks a lot, that's much useful information for me as a rookie :)

**Comment by anthonyfok** [comment]
Oh, one more problem which I fixed in a second commit...

 * https://yulinling.net/ → http://yulinling.net/

(CSS and images won't load for https)

Next time, try to test it before you submit the pull request.  :wink:
You may test your change to Hugo docs locally by using this command:

    hugo -s docs server

and then opening http://localhost:1313/showcase/ on your web browser.

**Comment by Lynxiayel** [comment]
@anthonyfok  Thank you, it's nice to know :)

**Pull request closed without merging**
