### PR TITLE
Add in-section Next/Prev section pointers

### PR DESCRIPTION
**Pull request by johnsto**
Allows navigation to be added to pages that is restricted to the current section.

Templates can use `.PrevInSection` and `.NextInSection` in the same way they use `.Prev` and `.Next`.

Issue: #211

(Moved from #259)

### CODE REVIEW

**Comment by bjornerik** [comment]
I'll reopen this as this is functionality that I miss, a very common use case and not really "added via b719ba7".

**Comment by moorereason** [comment]
Thanks for reopening, @bjornerik.  This is an important missing feature.

@spf13 already declined to merge this PR, and I tend to agree with him that this PR is not the best (idiomatic?) long term solution (even though I've applied this PR locally).  [I posted some ideas](http://discuss.gohugo.io/t/proposals-for-next-prev-in-section/434) to the dev discussion forum last month, but I didn't get any feedback.  Perhaps we could find a better solution.

@spf13, care to comment here or in the discussion forum on what you'd like to see instead of this PR?

**Comment by bjornerik** [comment]
Not sure what "idomatic" means in this context -- I understand the concern about polluting the structs with very specific fields, favoring more generic functions that can be mixed and matched.

But this is a very common use case, and people "guessing the API" without looking at the doc would probably try your implementation.

To quote John Carmack (the man behind Doom): 

"If you’re willing to restrict the flexibility of your approach, you can almost always do something better."

**Comment by bjornerik** [comment]
@spf13 I have now started using this patch myself, and I hate having too many custom patches going on (the branching confuses me ...) ... The implementation looks clean enough -- I'm going to merge this if you don't shout in a day or so; the acceptance of silence :-)

**Comment by spf13** [comment]
I'm fine with this overall. I agree that it's a common enough use case to call it out specifically. 

I don't love the current method names, but I can think of a better one.

We should make sure to document clearly that there is a general way to get Prev & Next and we've provided two shortcuts (global & section).

**Comment by bjornerik** [comment]
The one who waits for something good ... Merged in a5f5106 - thanks!

**Pull request closed without merging**
