### PR TITLE
Make absURL properly handle baseURL with path component

### PR DESCRIPTION
**Pull request by mjanda**

### CODE REVIEW

**Comment by mjanda** [comment]
Regarding previous coment about panic(). Not sure how can I return an error without breaking everything that already uses AbsURL. And at this point, it doesn't even make a difference. If it wouldn't panic here, it would be passed to MakePermalink and panic there.

Other changes - done.

**Comment by bep** [comment]
>Regarding previous coment about panic(). Not sure how can I return an error without breaking everything that already uses AbsURL. 

It is used in one (1) place. The templates are fine with this as long as you add the error as the second return value. Then you can more easily test for it, too.

**Comment by mjanda** [comment]
Ok, I've looked at it and I'm still not sure about it.

If this is triggered, than your site configuration is invalid (we're parsing BaseURL, not something content-related) and there's no way to fix it.

Returning error would make sense to me if there was any chance you could do something about it, but this seems like pushing unfixable problem around.

And consider current behavior (triggered later in MakePermalink):
- invalid baseURL -> panic()
- invalid path -> panic()

You're proposing change to
- invalid baseURL -> return error
- invalid path -> panic()

I think keeping it consistent would be better...someone might later add recover() on some level where it makes sense and handle it all together (still, I think invalid site configuration isn't something you can/should recover from).

Another approach might be to sidestep the problem completely and pass that invalid baseURL to MakePermalink as is:
```
if err == nil {
   p.Path = ""
   baseURL = p.String()
}
```

**Comment by bep** [comment]
Having user-facing functions panic on bad user input (even if it is in the configuration) is bad.

Consider these log statements from the template func `slicestr` (I modded the code a little):

```
ERROR: 2015/11/03 Error while rendering page post/wp/2010-05-05-varyre-sauer-darlege-fotballspelarar.md: template: partials/footer.html:2:3: executing "partials/footer.html" at <slicestr "hello worl...>: error calling slicestr: This is a nice and informative error!
``

And a panic in the same func:

```
panic: This is a nice and informative error! [recovered]
	panic: This is a nice and informative error!

goroutine 213 [running]:
text/template.errRecover(0xc820893848)
	/usr/local/go/src/text/template/exec.go:104 +0x15b
github.com/spf13/hugo/tpl.Slicestr(0x5a33e0, 0xc8205d9480, 0xc82025f4c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/template_funcs.go:158 +0xfa
reflect.Value.call(0x665e60, 0x8ceaf0, 0x13, 0x766558, 0x4, 0xc8202539b0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x665e60, 0x8ceaf0, 0x13, 0xc82059a460, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
text/template.(*state).evalCall(0xc8208933e8, 0x730380, 0xc820533320, 0x16, 0x665e60, 0x8ceaf0, 0x13, 0x1960c60, 0xc8202d6270, 0xc8202695a1, ...)
	/usr/local/go/src/text/template/exec.go:602 +0xb38
text/template.(*state).evalFunction(0xc8208933e8, 0x730380, 0xc820533320, 0x16, 0xc8202d62a0, 0x1960c60, 0xc8202d6270, 0xc8202c8f40, 0x4, 0x4, ...)
	/usr/local/go/src/text/template/exec.go:475 +0x33d
text/template.(*state).evalCommand(0xc8208933e8, 0x730380, 0xc820533320, 0x16, 0xc8202d6270, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:372 +0x1e9
text/template.(*state).evalPipeline(0xc8208933e8, 0x730380, 0xc820533320, 0x16, 0xc8202c3ae0, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:345 +0x180
text/template.(*state).walk(0xc8208933e8, 0x730380, 0xc820533320, 0x16, 0xc6b808, 0xc8202d62d0)
	/usr/local/go/src/text/template/exec.go:180 +0x135
text/template.(*state).walk(0xc8208933e8, 0x730380, 0xc820533320, 0x16, 0x1960478, 0xc8202d6210)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*state).walkTemplate(0xc8208937d8, 0x730380, 0xc820533320, 0x16, 0xc82029a100)
	/usr/local/go/src/text/template/exec.go:328 +0x417
text/template.(*state).walk(0xc8208937d8, 0x730380, 0xc820533320, 0x16, 0x1960430, 0xc82029a100)
	/usr/local/go/src/text/template/exec.go:193 +0x68c
text/template.(*state).walk(0xc8208937d8, 0x730380, 0xc820533320, 0x16, 0x1960478, 0xc8202834d0)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*Template).Execute(0xc820261f00, 0xca7ed0, 0xc82019f6c0, 0x730380, 0xc820533320, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:143 +0x2b6
html/template.(*Template).ExecuteTemplate(0xc820215b40, 0xca7ed0, 0xc82019f6c0, 0x7d62e0, 0x12, 0x730380, 0xc820533320, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:118 +0xb7
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc82018ca80, 0x730380, 0xc820533320, 0x7d62e0, 0x12, 0xca7ed0, 0xc82019f6c0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1515 +0x215
github.com/spf13/hugo/hugolib.(*Site).render(0xc82018ca80, 0xc8201370a0, 0xc, 0x730380, 0xc820533320, 0xc82019f6c0, 0xc820340ec0, 0x4, 0x4, 0x0, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1490 +0x2f8
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc82018ca80, 0xc8201370a0, 0xc, 0xc82015fac0, 0x1b, 0x730380, 0xc820533320, 0xc820340ec0, 0x4, 0x4, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1441 +0xde
github.com/spf13/hugo/hugolib.taxonomyRenderer(0xc82018ca80, 0xc8203f4480, 0xc8203f44e0, 0xc8201364d0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1088 +0x4c6
created by github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1019 +0x120

goroutine 1 [chan send]:
github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists(0xc82018ca80, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1029 +0x3b5
github.com/spf13/hugo/hugolib.(*Site).Render(0xc82018ca80, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:387 +0x83
github.com/spf13/hugo/hugolib.(*Site).Build(0xc82018ca80, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:244 +0x80
github.com/spf13/hugo/commands.buildSite(0xc82089b95f, 0x1, 0x1, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/commands/hugo.go:426 +0xcf
github.com/spf13/hugo/commands.build(0xc82089baa6, 0x1, 0x1)
	/Users/bep/go/src/github.com/spf13/hugo/commands/hugo.go:321 +0x2a8
github.com/spf13/hugo/commands.server(0xafe020, 0xc820020720, 0x0, 0x6)
	/Users/bep/go/src/github.com/spf13/hugo/commands/server.go:123 +0x604
github.com/spf13/cobra.(*Command).execute(0xafe020, 0xc820020660, 0x6, 0x6, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/cobra/command.go:555 +0x869
github.com/spf13/cobra.(*Command).Execute(0xafcb80, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/cobra/command.go:640 +0x48e
github.com/spf13/hugo/commands.Execute()
	/Users/bep/go/src/github.com/spf13/hugo/commands/hugo.go:70 +0x44
main.main()
	/Users/bep/go/src/github.com/spf13/hugo/main.go:24 +0x28

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 212 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1019 +0x120

goroutine 211 [runnable]:
sync.runtime_Semacquire(0xb04f6c)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*RWMutex).RLock(0xb04f60)
	/usr/local/go/src/sync/rwmutex.go:36 +0x58
reflect.funcLayout(0x5f43a0, 0x0, 0xc820096358, 0x1, 0xc82025fa00, 0x1, 0x1)
	/usr/local/go/src/reflect/type.go:2046 +0x19a
reflect.Value.call(0x5f43a0, 0x8cee58, 0x13, 0x766558, 0x4, 0xc82025faa0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:397 +0xe7d
reflect.Value.Call(0x5f43a0, 0x8cee58, 0x13, 0xc82025fa00, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
text/template.(*state).evalCall(0xc8200973e8, 0x70dd20, 0xc8202760b8, 0xd6, 0x5f43a0, 0x8cee58, 0x13, 0x1960c60, 0xc820302720, 0x7dea00, ...)
	/usr/local/go/src/text/template/exec.go:602 +0xb38
text/template.(*state).evalFunction(0xc8200973e8, 0x70dd20, 0xc8202760b8, 0xd6, 0xc8203026f0, 0x1960c60, 0xc820302720, 0xc8205e2760, 0x1, 0x1, ...)
	/usr/local/go/src/text/template/exec.go:475 +0x33d
text/template.(*state).evalCommand(0xc8200973e8, 0x70dd20, 0xc8202760b8, 0xd6, 0xc820302720, 0x5a33e0, 0xc820306240, 0xd8, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:372 +0x1e9
text/template.(*state).evalPipeline(0xc8200973e8, 0x70dd20, 0xc8202760b8, 0xd6, 0xc8202f8550, 0x5a33e0, 0xc820306240, 0xd8)
	/usr/local/go/src/text/template/exec.go:345 +0x180
text/template.(*state).walk(0xc8200973e8, 0x70dd20, 0xc8202760b8, 0xd6, 0xc6b808, 0xc8202edd40)
	/usr/local/go/src/text/template/exec.go:180 +0x135
text/template.(*state).walk(0xc8200973e8, 0x70dd20, 0xc8202760b8, 0xd6, 0x1960478, 0xc8202edb60)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*state).walkRange.func1(0x5a28e0, 0xc8205d9570, 0x42, 0x70dd20, 0xc8202760b8, 0xd6)
	/usr/local/go/src/text/template/exec.go:270 +0x202
text/template.(*state).walkRange(0xc8200973e8, 0x730380, 0xc82088aea0, 0x16, 0xc8202fe200)
	/usr/local/go/src/text/template/exec.go:279 +0x46c
text/template.(*state).walk(0xc8200973e8, 0x730380, 0xc82088aea0, 0x16, 0xcadae0, 0xc8202fe200)
	/usr/local/go/src/text/template/exec.go:191 +0x264
text/template.(*state).walk(0xc8200973e8, 0x730380, 0xc82088aea0, 0x16, 0x1960478, 0xc8202ed8f0)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*state).walkTemplate(0xc8200977d8, 0x730380, 0xc82088aea0, 0x16, 0xc82029a040)
	/usr/local/go/src/text/template/exec.go:328 +0x417
text/template.(*state).walk(0xc8200977d8, 0x730380, 0xc82088aea0, 0x16, 0x1960430, 0xc82029a040)
	/usr/local/go/src/text/template/exec.go:193 +0x68c
text/template.(*state).walk(0xc8200977d8, 0x730380, 0xc82088aea0, 0x16, 0x1960478, 0xc8202834d0)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*Template).Execute(0xc820261f00, 0xca7ed0, 0xc8206393b0, 0x730380, 0xc82088aea0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:143 +0x2b6
html/template.(*Template).ExecuteTemplate(0xc820215b40, 0xca7ed0, 0xc8206393b0, 0x7d62e0, 0x12, 0x730380, 0xc82088aea0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:118 +0xb7
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc82018ca80, 0x730380, 0xc82088aea0, 0x7d62e0, 0x12, 0xca7ed0, 0xc8206393b0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1515 +0x215
github.com/spf13/hugo/hugolib.(*Site).render(0xc82018ca80, 0xc820013f00, 0xc, 0x730380, 0xc82088aea0, 0xc8206393b0, 0xc8202e5c40, 0x4, 0x4, 0x0, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1490 +0x2f8
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc82018ca80, 0xc820013f00, 0xc, 0xc820608cc0, 0x1a, 0x730380, 0xc82088aea0, 0xc8202e5c40, 0x4, 0x4, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1441 +0xde
github.com/spf13/hugo/hugolib.taxonomyRenderer(0xc82018ca80, 0xc8203f4480, 0xc8203f44e0, 0xc8201364d0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1088 +0x4c6
created by github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1019 +0x120

goroutine 214 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1019 +0x120

goroutine 215 [chan receive]:
github.com/spf13/hugo/hugolib.errorCollator(0xc8203f44e0, 0xc8203f4540)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:959 +0x96
created by github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1024 +0x174
panic: This is a nice and informative error! [recovered]
	panic: This is a nice and informative error!

goroutine 212 [running]:
text/template.errRecover(0xc8202bb848)
	/usr/local/go/src/text/template/exec.go:104 +0x15b
github.com/spf13/hugo/tpl.Slicestr(0x5a33e0, 0xc8207cec70, 0xc8203f04a0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/template_funcs.go:158 +0xfa
reflect.Value.call(0x665e60, 0x8ceaf0, 0x13, 0x766558, 0x4, 0xc8201974a0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x665e60, 0x8ceaf0, 0x13, 0xc820015270, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
text/template.(*state).evalCall(0xc8202bb3e8, 0x730380, 0xc8204ecd80, 0x16, 0x665e60, 0x8ceaf0, 0x13, 0x1960c60, 0xc8202d6270, 0xc8202695a1, ...)
	/usr/local/go/src/text/template/exec.go:602 +0xb38
text/template.(*state).evalFunction(0xc8202bb3e8, 0x730380, 0xc8204ecd80, 0x16, 0xc8202d62a0, 0x1960c60, 0xc8202d6270, 0xc8202c8f40, 0x4, 0x4, ...)
	/usr/local/go/src/text/template/exec.go:475 +0x33d
text/template.(*state).evalCommand(0xc8202bb3e8, 0x730380, 0xc8204ecd80, 0x16, 0xc8202d6270, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:372 +0x1e9
text/template.(*state).evalPipeline(0xc8202bb3e8, 0x730380, 0xc8204ecd80, 0x16, 0xc8202c3ae0, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:345 +0x180
text/template.(*state).walk(0xc8202bb3e8, 0x730380, 0xc8204ecd80, 0x16, 0xc6b808, 0xc8202d62d0)
	/usr/local/go/src/text/template/exec.go:180 +0x135
text/template.(*state).walk(0xc8202bb3e8, 0x730380, 0xc8204ecd80, 0x16, 0x1960478, 0xc8202d6210)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*state).walkTemplate(0xc8202bb7d8, 0x730380, 0xc8204ecd80, 0x16, 0xc82029a100)
	/usr/local/go/src/text/template/exec.go:328 +0x417
text/template.(*state).walk(0xc8202bb7d8, 0x730380, 0xc8204ecd80, 0x16, 0x1960430, 0xc82029a100)
	/usr/local/go/src/text/template/exec.go:193 +0x68c
text/template.(*state).walk(0xc8202bb7d8, 0x730380, 0xc8204ecd80, 0x16, 0x1960478, 0xc8202834d0)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*Template).Execute(0xc820261f00, 0xca7ed0, 0xc8204253b0, 0x730380, 0xc8204ecd80, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:143 +0x2b6
html/template.(*Template).ExecuteTemplate(0xc820215b40, 0xca7ed0, 0xc8204253b0, 0x7d62e0, 0x12, 0x730380, 0xc8204ecd80, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:118 +0xb7
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc82018ca80, 0x730380, 0xc8204ecd80, 0x7d62e0, 0x12, 0xca7ed0, 0xc8204253b0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1515 +0x215
github.com/spf13/hugo/hugolib.(*Site).render(0xc82018ca80, 0xc8205c11a0, 0xc, 0x730380, 0xc8204ecd80, 0xc8204253b0, 0xc82031eb00, 0x4, 0x4, 0x0, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1490 +0x2f8
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc82018ca80, 0xc8205c11a0, 0xc, 0xc8202a85a0, 0x13, 0x730380, 0xc8204ecd80, 0xc82031eb00, 0x4, 0x4, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1441 +0xde
github.com/spf13/hugo/hugolib.taxonomyRenderer(0xc82018ca80, 0xc8203f4480, 0xc8203f44e0, 0xc8201364d0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1088 +0x4c6
created by github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1019 +0x120
panic: This is a nice and informative error! [recovered]
	panic: This is a nice and informative error!

goroutine 214 [running]:
text/template.errRecover(0xc8202bf848)
	/usr/local/go/src/text/template/exec.go:104 +0x15b
github.com/spf13/hugo/tpl.Slicestr(0x5a33e0, 0xc820803670, 0xc8207d8c80, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/template_funcs.go:158 +0xfa
reflect.Value.call(0x665e60, 0x8ceaf0, 0x13, 0x766558, 0x4, 0xc82014afc0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x665e60, 0x8ceaf0, 0x13, 0xc8201354a0, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
text/template.(*state).evalCall(0xc8202bf3e8, 0x730380, 0xc82010d320, 0x16, 0x665e60, 0x8ceaf0, 0x13, 0x1960c60, 0xc8202d6270, 0xc8202695a1, ...)
	/usr/local/go/src/text/template/exec.go:602 +0xb38
text/template.(*state).evalFunction(0xc8202bf3e8, 0x730380, 0xc82010d320, 0x16, 0xc8202d62a0, 0x1960c60, 0xc8202d6270, 0xc8202c8f40, 0x4, 0x4, ...)
	/usr/local/go/src/text/template/exec.go:475 +0x33d
text/template.(*state).evalCommand(0xc8202bf3e8, 0x730380, 0xc82010d320, 0x16, 0xc8202d6270, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:372 +0x1e9
text/template.(*state).evalPipeline(0xc8202bf3e8, 0x730380, 0xc82010d320, 0x16, 0xc8202c3ae0, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:345 +0x180
text/template.(*state).walk(0xc8202bf3e8, 0x730380, 0xc82010d320, 0x16, 0xc6b808, 0xc8202d62d0)
	/usr/local/go/src/text/template/exec.go:180 +0x135
text/template.(*state).walk(0xc8202bf3e8, 0x730380, 0xc82010d320, 0x16, 0x1960478, 0xc8202d6210)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*state).walkTemplate(0xc8202bf7d8, 0x730380, 0xc82010d320, 0x16, 0xc82029a100)
	/usr/local/go/src/text/template/exec.go:328 +0x417
text/template.(*state).walk(0xc8202bf7d8, 0x730380, 0xc82010d320, 0x16, 0x1960430, 0xc82029a100)
	/usr/local/go/src/text/template/exec.go:193 +0x68c
text/template.(*state).walk(0xc8202bf7d8, 0x730380, 0xc82010d320, 0x16, 0x1960478, 0xc8202834d0)
	/usr/local/go/src/text/template/exec.go:188 +0x776
text/template.(*Template).Execute(0xc820261f00, 0xca7ed0, 0xc8204255e0, 0x730380, 0xc82010d320, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:143 +0x2b6
html/template.(*Template).ExecuteTemplate(0xc820215b40, 0xca7ed0, 0xc8204255e0, 0x7d62e0, 0x12, 0x730380, 0xc82010d320, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:118 +0xb7
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc82018ca80, 0x730380, 0xc82010d320, 0x7d62e0, 0x12, 0xca7ed0, 0xc8204255e0, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1515 +0x215
github.com/spf13/hugo/hugolib.(*Site).render(0xc82018ca80, 0xc8205d8e00, 0xc, 0x730380, 0xc82010d320, 0xc8204255e0, 0xc82016f440, 0x4, 0x4, 0x0, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1490 +0x2f8
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc82018ca80, 0xc8205d8e00, 0xc, 0xc82025e600, 0x1e, 0x730380, 0xc82010d320, 0xc82016f440, 0x4, 0x4, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1441 +0xde
github.com/spf13/hugo/hugolib.taxonomyRenderer(0xc82018ca80, 0xc8203f4480, 0xc8203f44e0, 0xc8201364d0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1088 +0x4c6
created by github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1019 +0x120
```

**Comment by bep** [comment]
Never mind, just keep the panic. If the baseURL is wrong, it should be caught earlier.

**Comment by bep** [comment]
Merged in 0962470

**Pull request closed without merging**
