### PR TITLE
Showcase addition - worldtowriters.com

### PR DESCRIPTION
**Pull request by luxpir**
Thanks for Hugo - fantastic software.

### CODE REVIEW

**Comment by bep** [comment]
Very nice site, but I find it slightly ironic that you don't use Hugo's multilingual feature :-)

**Comment by luxpir** [comment]
I know, I know :) Target clients are here in the UK, so monolingual is about right!

It's definitely what drew me back into using Hugo, was v v happy to hear about the feature. The Universal theme even bundles a few pre-translations - just figuring out how to enable them. Thought they might be menu/site translations while the content could be translated separately... unless it's my nginx config that needs /de /es allowing. Will investigate!

**Comment by lebarde** [comment]
Very nice site! So in the end, what theme did you choose?

**Comment by luxpir** [comment]
Gah, didn't say, did I... It's http://themes.gohugo.io/theme/hugo-universal-theme/ - looks great out of the box. As I said in the post, have to focus on content now and getting my SEO traffic up!

**Comment by lebarde** [comment]
Very nice! So, good luck for your content management and traffic!

**Comment by digitalcraftsman** [comment]
Hello @luxpir 

thank you for adding your website to the showcase of Hugo. I've merged your contribution as  6fc7337a. Hugo's showcase section should be updated within the next minutes.

Cheers,
Digitalcraftsman

**Pull request closed without merging**
