### PR TITLE
Added command exec shortcode. See #796

### PR DESCRIPTION
**Pull request by tubo028**
Currently what it can is receive 2 arguments (the command and options) and then insert stdout to the called point. Flowing inner text into stdin is not now.
Whitelist is configurable and only `cat` (for unix) and `type` (for windows) are available in default.

Now I am trying it on [my site](http://tubo28.me/). Just `cat` command reduced so many copy and paste on the source.
I am looking forwarding to being it official.

### CODE REVIEW

**Comment by bep** [comment]
Can you fix the commit message to be in line with guidelines? (it's ok to amend your commit and do a push -f).

**Comment by tubo028** [comment]
I done it, but my English ugly. Please point out them if unacceptable...

**Comment by bep** [comment]
The English is just fine, and now the commit message looks good.

**Comment by digitalcraftsman** [comment]
It would be great if you could add a few words about your new shortcodes in documentantions

**Comment by moorereason** [comment]
I'm curious if we can write tests for this, as well.

**Comment by tubo028** [comment]
You mean making a commit which adds description of the shortcode and some test codes?
I can write the documentation but I have not written any test codes, so I may be going to ask for help.

**Comment by digitalcraftsman** [comment]
> You mean making a commit which adds description of the shortcode and some test codes?

That would be nice additions before we merging it.

We should at least add some test cases for the allowed default commands `cat` and `type`. We could test `cat` easily with a temporary file that is created during the test. The ouput of cat and the written content should be the same.

Does anyone has some good ideas for other test cases?

**Pull request closed without merging**
