### PR TITLE
Get rid of some viper.Get* calls

### LINKED ISSUE #3060: Get rid of viper.Get(canonifyurls)
See https://github.com/spf13/hugo/issues/2728

### PR DESCRIPTION
**Pull request by bogem**
Enforce usage of PathSpec

Fixes #3060
Updates #2728

Viper usage:
**examples/blog**
```
  47 baseurl
  31 relativeurls
  23 languages
  22 builddrafts
  20 buildfuture
  20 buildexpired
  18 disablerss
  16 ignorefiles
  11 blackfriday
  10 usemodtimeasfallback
  10 publishdir
  10 hascjklanguage
  10 footnotereturnlinkcontents
  10 footnoteanchorprefix
  10 enableemoji
   8 taxonomies
   8 rssuri
   7 defaultcontentlanguage
   6 rsslimit
   5 sitemap
   4 uglyurls
   4 theme
   4 multilingual
   4 defaultextension
   4 defaultcontentlanguageinsubdir
   4 canonifyurls
   3 workingDir
   3 disablesitemap
   3 defaultContentLanguage
   3 baseURL
   2 workingdir
   2 uglyURLs
   2 themesdir
   2 themesDir
   2 staticdir
   2 staticDir
   2 social
   2 sectionpagesmenu
   2 removepathaccents
   2 removePathAccents
   2 preservetaxonomynames
   2 pluralizelisttitles
   2 permalinks
   2 params
   2 paginatepath
   2 paginatePath
   2 layoutdir
   2 layoutDir
   2 languagecode
   2 googleanalytics
   2 enablerobotstxt
   2 disqusshortname
   2 disablepathtolower
   2 disablekinds
   2 disablehugogeneratorinject
   2 disablePathToLower
   2 disable404
   2 defaultContentLanguageInSubdir
   2 copyright
   2 contentdir
   2 canonifyURLs
   2 author
   1 verbose
   1 relativeURLs
   1 publishDir
   1 noTimes
   1 noChmod
   1 logFile
   1 i18ndir
   1 enablemissingtranslationplaceholders
   1 enablegitinfo
   1 datadir
   1 cleanDestinationDir
   1 cacheDir
```
---
**examples/multilingual**
```
  47 baseurl
  31 relativeurls
  23 languages
  22 builddrafts
  20 buildfuture
  20 buildexpired
  18 disablerss
  16 ignorefiles
  11 blackfriday
  10 usemodtimeasfallback
  10 publishdir
  10 hascjklanguage
  10 footnotereturnlinkcontents
  10 footnoteanchorprefix
  10 enableemoji
   8 taxonomies
   8 rssuri
   7 defaultcontentlanguage
   6 rsslimit
   5 sitemap
   4 uglyurls
   4 theme
   4 multilingual
   4 defaultextension
   4 defaultcontentlanguageinsubdir
   4 canonifyurls
   3 workingDir
   3 disablesitemap
   3 defaultContentLanguage
   3 baseURL
   2 workingdir
   2 uglyURLs
   2 themesdir
   2 themesDir
   2 staticdir
   2 staticDir
   2 social
   2 sectionpagesmenu
   2 removepathaccents
   2 removePathAccents
   2 preservetaxonomynames
   2 pluralizelisttitles
   2 permalinks
   2 params
   2 paginatepath
   2 paginatePath
   2 layoutdir
   2 layoutDir
   2 languagecode
   2 googleanalytics
   2 enablerobotstxt
   2 disqusshortname
   2 disablepathtolower
   2 disablekinds
   2 disablehugogeneratorinject
   2 disablePathToLower
   2 disable404
   2 defaultContentLanguageInSubdir
   2 copyright
   2 contentdir
   2 canonifyURLs
   2 author
   1 verbose
   1 relativeURLs
   1 publishDir
   1 noTimes
   1 noChmod
   1 logFile
   1 i18ndir
   1 enablemissingtranslationplaceholders
   1 enablegitinfo
   1 datadir
   1 cleanDestinationDir
   1 cacheDir
```
---
**docs**
```
 596 pygmentscodefences
 455 relativeurls
 441 baseurl
 434 defaultcontentlanguage
 431 languages
 429 builddrafts
 428 buildfuture
 428 buildexpired
 374 defaultextension
 301 disablerss
 231 ignorefiles
 215 blackfriday
 214 hascjklanguage
 214 footnotereturnlinkcontents
 214 footnoteanchorprefix
 214 enableemoji
  88 rssuri
  87 rsslimit
  11 pluralizelisttitles
   5 publishdir
   4 taxonomies
   4 defaultContentLanguage
   3 workingDir
   3 theme
   3 multilingual
   3 contentdir
   3 baseURL
   2 workingdir
   2 uglyurls
   2 uglyURLs
   2 themesDir
   2 staticDir
   2 removePathAccents
   2 paginatePath
   2 layoutDir
   2 disablePathToLower
   2 defaultcontentlanguageinsubdir
   2 defaultContentLanguageInSubdir
   2 canonifyurls
   2 canonifyURLs
   1 verbose
   1 title
   1 themesdir
   1 staticdir
   1 social
   1 sitemap
   1 sectionpagesmenu
   1 removepathaccents
   1 relativeURLs
   1 publishDir
   1 preservetaxonomynames
   1 permalinks
   1 params
   1 paginatepath
   1 noTimes
   1 noChmod
   1 menu
   1 logFile
   1 layoutdir
   1 languagecode
   1 i18ndir
   1 googleanalytics
   1 enablerobotstxt
   1 enablemissingtranslationplaceholders
   1 enablegitinfo
   1 disqusshortname
   1 disablesitemap
   1 disablepathtolower
   1 disablekinds
   1 disablehugogeneratorinject
   1 disable404
   1 datadir
   1 copyright
   1 cleanDestinationDir
   1 cacheDir
```

### CODE REVIEW

**Comment by bep** [comment]
Pretty good effect for small amount of work in my benchmark:

```
benchmark           old ns/op      new ns/op      delta
BenchmarkHugo-4     9623753236     9264761669     -3.73%

benchmark           old allocs     new allocs     delta
BenchmarkHugo-4     43342841       42696420       -1.49%

benchmark           old bytes      new bytes      delta
BenchmarkHugo-4     9084994152     9065991096     -0.21%
```

**Comment by bogem** [comment]
Hm, it's very interesting, how viper really badly affects on the performance and memory consumption.

**Comment by bep** [comment]
Yes, but according to your latest numbers, we have removed the bottle necks now.

This is the benchmarks from the Viper project:

```
BenchmarkGetBool-4          	 3000000	       426 ns/op	      65 B/op	       5 allocs/op
BenchmarkGet-4              	 5000000	       373 ns/op	      64 B/op	       5 allocs/op
BenchmarkGetBoolFromMap-4   	200000000	         6.36 ns/op	       0 B/op	       0 allocs/op
````
And while 400 ns is 60 times slower than a map lookup, you would need lots of them to notice.

Which means, we should continue to clean up -- but only if it actually gets cleaner, not by making lots of local variables around the place.

**Comment by bogem** [comment]
Ok, I understood you. I will try to just enforce PathSpecs or delete really redundant viper calls.

**Pull request merged**
