### PR TITLE
Explicitly bind livereload to hugo server port, fixes #2205

### LINKED ISSUE #2205: Websocket for LiveReload using wrong port if Hugo binds to port 80
Let's say I clone this repo:

```
git clone https://github.com/robertbasic/robertbasic.com-hugo.git
```

Then start up a docker container on Hugo 0.16:

```
docker run -ti --rm --name "my-hugo" \
  -p 80:80 -v $(pwd)/robertbasic.com-hugo:/src jojomi/hugo \
  hugo server --watch=true --source="/src" --bind=0.0.0.0 --port=80 --baseURL="/"
```

Where I have watch on and I'm listening on port 80. When you load the site, you get:

```
WebSocket connection to 'ws://192.168.51.1:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Which is clearly trying to connect to the hugo server on the wrong port. If you pop the port number up one value:

```
docker run -ti --rm --name "my-hugo" \
  -p 81:81 -v $(pwd)/robertbasic.com-hugo:/src jojomi/hugo \
  hugo server --watch=true --source="/src" --bind=0.0.0.0 --port=81 --baseURL="/"
```

It works as expected (from chrome console):

```
Request URL:ws://192.168.51.1:81/livereload
Request Method:GET
Status Code:101 Switching Protocols
```

Originally discussed and discovered here: https://discuss.gohugo.io/t/live-reload-unconnectable-in-docker-container/3457/4

### PR DESCRIPTION
**Pull request by dplesca**

### CODE REVIEW

**Comment by moorereason** [comment]
Be sure to run tests before submitting PRs.

You need to set the port via viper before running tests.  For an example, [look here](https://github.com/spf13/hugo/blob/64817cc0d125f99e69c5a8c77d21e97e52ab23d9/tpl/template_funcs_test.go#L71).

**Comment by dplesca** [comment]
@moorereason Thanks for the tip, it should be ok now.

**Comment by bep** [comment]
Please fix the commit message.

**Comment by dplesca** [comment]
@bep does it look ok now?

**Comment by moorereason** [comment]
No.  Commit message should be:

```
transform: Explicitly bind livereload to server port

Fixes #2205
```

**Comment by dplesca** [comment]
Hi again, I hope it's alright now, sorry if I didn't get the rules from the start and wasted everyone's time.

**Comment by anthonyfok** [comment]
Thank you for your contribution, @dplesca!  I made some minor changes to the commit message, and gave partial credit @chuyskywalker.

Merged as 7e08d23.

**Pull request closed without merging**
