### PR TITLE
fix README : current way to set hugo revision could be decapricated soon

### PR DESCRIPTION
**Pull request by mikefaille**
and cleaning empty space. (whitespace-mode from emacs)

Warning from git version 2.7.0 :

```
link: warning: option -X /path/to/hugo/hugolib.CommitHash 868d074 may not work in future releases; use -X /path/to/hugo/hugolib.CommitHash=868d074
link: warning: option -X github.com/spf13/hugo/hugolib.BuildDate 2016-02-04T12:23:41-0500 may not work in future releases; use -X github.com/spf13/hugo/hugolib.BuildDate=2016-02-04T12:23:41-0500
```

### CODE REVIEW

**Comment by anthonyfok** [comment]
Hi @mikefaille,

Thank you for your attention to details and for your contribution!

Just a few notes:

1. It turns out to be a known problem that was fixed in #1365 in August 2015, though only the `Makefile` was fixed back then.
2. The warning comes not from Git 2.7.0 but from Go 1.5 and above.
3. It is spelled "deprecated", not "decapricated", but no worries, I will amend the commit message before pushing it to `master`.

**Comment by anthonyfok** [comment]
Merged as 08670e6.

**Comment by mikefaille** [comment]
Thank you !
( from Quebecer who gains currently gain English skills )

**Comment by anthonyfok** [comment]
Merci beaucoup !
(from an Albertan who would love to learn more French)  :-)

**Pull request closed without merging**
