### PR TITLE
helpers, hugolib, tpl: Get rid of ConfigProvider

### PR DESCRIPTION
**Pull request by bogem**
Less abstraction, more simplicity, more performance.

`hugo benchmark -n 30 -s examples/multilingual` before:
```
Average time per operation: 22ms
Average memory allocated per operation: 1933kB
Average allocations per operation: 30286
```

after:
```
Average time per operation: 19ms
Average memory allocated per operation: 1920kB
Average allocations per operation: 30150
```

It's just concept, but fully-working (at least it passes the tests). 

See https://github.com/spf13/hugo/issues/2728#issuecomment-262789492

More tests should be added before the merging.

### CODE REVIEW

**Comment by bep** [comment]
What do you suggest we do when we want to add more *Spec types?

**Comment by bogem** [comment]
Use `New*SpecFromCurrentLanguage` or `New*SpecFromViper`

**Comment by bep** [comment]
There are several problems with your approach. At first glance it looks like a DRY problem, but that could be OK, although duplicating the property reading in the New funcs is error phrone. 

But that also leads to using a totally different code path in many of the tests vs real code.

I think the ConfigProvider is a nice and needed abstraction. I'm not sure what your benchmarks really show / do, but I'm pretty sure that this isn't worth it.

**Comment by bogem** [comment]
Yes, the duplication is a problem and the obvious solution is usage of some abstraction (like `ConfigProvider`) but I thought, what this problem could be solved in more elegant way than one more abstraction. But my solution is also not an elegant way though.

**Comment by bogem** [comment]
And what did you mean [here](https://github.com/spf13/hugo/pull/2731/files#diff-2fd22c31939cd0e842f01d0bd044c980L29)? What should be get rid of?

**Comment by bogem** [comment]
The problem of duplication in my PR could be solved by using the `viper` as empty `Language`, so all `Get*` calls will be redirected to `viper`, although it's a workaround😅
`helpers/pathspec.go`
```
...
func NewPathSpecFromViper() *PathSpec {
    l := helpers.Language{}
    return NewPathSpecFromLanguage(l)
}
...
```

**Comment by bep** [comment]
>calls will be redirected to viper, although it's a workaround

We don't do workarounds when we don't have to. The existing solution is fine, this doesn't move the issue you starting anywhere closer to a fix. The `ConfigProvider` interface may show its value more clearly when we finish the #2701. 

In the future, you may save yourself some work by discussing your plan with others before spending too much time implementing it.

**Comment by bogem** [comment]
Ok, I'll try to contribute to fix #2701 issue and will discuss some ideas and solutions at first before the implementation.

**Comment by bep** [comment]
Just to make it clear: I appreciate your contributions, they show real potential, and there will lots of fun tasks to solve in Hugo in the near future, some of the fun being that it is actually being used by a lot of users.

**Comment by bogem** [comment]
Thank you, @bep 😌
Yes, I understand it :)

**Pull request closed without merging**
