### PR TITLE
source: Normalize file name to NFC

### LINKED ISSUE #2203: Static sync to memory fails with Norwegian "å"
* Image with Norwegian character "å", aka "ål.jpg" fails to sync in `hugo server`
* --renderToDisk works fine, as do regular hugo builds.
* Curious enough, files with "ø" (another special Norwegian character) works fine ...

### PR DESCRIPTION
**Pull request by ks888**
Fixes #2203

### CODE REVIEW

**Comment by bep** [comment]
This didn't fix my problem.

```
Darwin bep-mac.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

**Comment by bep** [comment]
This did https://github.com/spf13/fsync/pull/8

But this doesn't feel right.

**Comment by ks888** [comment]
Sorry this PR does not fix your issue. This PR works if an image file is under the `/content/` directory. I guess your image file is under the `/static/` directory, so this PR does not work.

Actually, this PR can fix the case a file (including markdown) under the `/content/` directory has `å` character. So I think this PR is still useful for non-English speakers like me.

**Comment by ks888** [comment]
@bep I fixed the merge conflict. Could you take a look this PR again?

**Pull request merged**
