### PR TITLE
docs: Add bharathpalavalli.com to the showcase

### PR DESCRIPTION
**Pull request by bmp**
* Created a personal website
* Adding website to showcase

### CODE REVIEW

**Comment by Jos512** [comment]
Not sure if we should add single-page websites with three paragraphs of text to the Hugo showcase. I don't think such sites are reflective of the possibilities and features that Hugo offers. Might even be off-putting to people considering Hugo.

**Comment by bmp** [comment]
Adding website design to Hugo-Showcase as suggested by the docs

**Comment by digitalcraftsman** [comment]
Hello @bmp,

thank you for adding your website to the showcase of Hugo. Please make sure that your pull requests doesn't accidently contains other commits / changes that aren't part of the showcase addition.

**Comment by bmp** [comment]
Hello, @digitalcraftsman 

I have only modified the Showcase folder as suggested in the docs available at https://www.gohugo.io/community/contributing/#showcase-additions. Please do let me know if you there is something extra or missing and I'll try and make those changes.

**Comment by digitalcraftsman** [comment]
The description for the showcase addition should be bullet-proof. You included somehow older commits that aren't related. Nonetheless, depending on you knowledge of Git it would be the easiest to do the following:

1. Create a new branch with `git checkout branch showcase2`
2. Copy the YAML file that you filed out as well as the screenshot of your website and save that at the locations named in the guide
4. Add the YAML file and screenshot both via `git add path/to/file.yaml`
3. Check with `git status` which files are tracked (those are highlighted green)
4. Make sure only your YAML file and screenshot are highlighted green
5. Create a new commit with `git commit -m"docs: Add bharathpalavalli.com to the showcase"`
6. Overwrite the commits that are currently mixed. You can use your new commit by overwriting the old one as follows: `git push --force --set-url origin bharathpalavalli-sc`

**Comment by bmp** [comment]
Hello @digitalcraftsman,

Thanks, I followed your instructions, and had a bit of a problem with,
`git checkout branch showcase2`
I am guessing you meant create a new branch showcase2 and checkout the branch. I did the same thing using,
`git checkout -b showcase-addition`
I then followed the guidelines at https://www.gohugo.io/community/contributing/#showcase-additions, to create the new post,
`hugo new showcase/bharathpalavalli.com.md`
I then followed your steps to add the .md file and the image,
`git add content/showcase/bharathpalavalli.com.md static/img/bharathpalavalli-tn.png `
After which I committed them with,
`git commit -m "docs: Add bharathpalavalli.com to the showcase"`

I had problems with `git push --force --set-url origin bharathpalavalli-sc`. Again, I am guessing you meant push the changes in the showcase branch to bharathpalavalli-sc. Therefore I had to follow these steps,
`git checkout bharathpalavalli-sc`
`git merge showcase-addition`
`git push origin bharathpalavalli-sc`

**Comment by digitalcraftsman** [comment]
> I am guessing you meant create a new branch showcase2 and checkout the branch. I did that with,
git checkout -b showcase-addition

You're correct.

> I had problems with git push --force --set-url origin bharathpalavalli-sc. Again, I am guessing you meant push the changes in the showcase branch to bharathpalavalli-sc.

`git push --force` should allow you to overwrite the commit history of the branch on GitHub. `--set-url`'s intended usecase was that the new branch `showcase2` should track the remote branch `bharathpalavalli-sc` which is used for this PR. I.e. 

Nonetheless, I merged your addition in c62220d3.

**Comment by bmp** [comment]
> Nonetheless, I merged your addition in c62220d.

Thank you.

**Pull request closed without merging**
