### PR TITLE
Added Images to sitemap.xml

### PR DESCRIPTION
**Pull request by derekperkins**
#655 This is dependent on image metadata being standardized as discussed at http://discuss.gohugo.io/t/hugo-seo-social-partials/353/17

### CODE REVIEW

**Comment by spf13** [comment]
@derekperkins I know you've been waiting a while on this one. Sorry it took me so long to get to it. It looks real nice. Merged as 3c147bd

**Comment by derekperkins** [comment]
No problem. There have been plenty of other fish to fry. :)

**Comment by spf13** [comment]
@derekperkins 

Now that this and the other PR have been merged can you add these new standards to the documentation?

We've gotten a bug report #972 about the sitemap being broken, but the problem isn't the template, but that the user had params.images as a string, here you expect it to have sub fields. 

We also should probably adjust the template to handle allowing users to just make params.images as a slice of strings.

**Comment by bep** [comment]
Have a look at the template_embedded.go that also uses  .Params.images and expect it to be a slice of string.

I suggest a revert of the above commit -- and do a rethinking and doc job of the complete picture.

**Comment by derekperkins** [comment]
There was a discussion started about standardizing metadata like images, but no conclusions were ever reached. I think we should make params.images something that we can expect. Somewhere I believe I submitted a PR that added Images as first class citizens to Node objects, or at least I thought about it. It's been a few months since I've done anything with Hugo.

**Comment by bep** [comment]
Closing this for now. Open a new one when we figure out what we want.

**Pull request closed without merging**
