### PR TITLE
Rickcogley showcase 20160201

### PR DESCRIPTION
**Pull request by RickCogley**
Updated site, so updated the showcase

### CODE REVIEW

**Comment by RickCogley** [comment]
Odd. I'd signed the CLA already.

**Comment by digitalcraftsman** [comment]
Hey @RickCogley,

> Odd. I'd signed the CLA already.

Did you changed the email in Git? It could be possible that this commit contains a new email address that isn't associated with your Github account. Github uses email addresses to identify and link user of in commits.

However, I've merged your update in 243fbbf0f96c89f3ac5b5a0c061d18e4473934cf (master) and 855d3cefde3c96b4f5445741e8aed2fd7bd4cd77 (v0.15.docs).

**Comment by RickCogley** [comment]
Hi @digitalcraftsman, no, I don't think I changed my email. I probably mis-clicked something. 

The above message says this was closed with un-merged commits. I noticed the screenshot is not showing. Anything I did wrong?

**Comment by digitalcraftsman** [comment]
> I noticed the screenshot is not showing. Anything I did wrong?

I don't think so. Locally, you changes work fine. Yesterday, I pushed other additions to the docs and those a currently live. Maybe is this a caching issue. 

A few weeks ago we updated some dependencies (Bootstrap, jQuery) and added some smaller modifications to the layout. @spf13 had to clear the Cloudflare cache in order to apply the changes. Maybe it's the same case here.

**Comment by anthonyfok** [comment]
Hi @RickCogley, when you have time, could you please make a new thumbnail image of your website?  It is the wrong size: The one you submitted a few days ago was 600×356 in pixels, while the requirement is 600×400 in pixels.  Many thanks!

**Comment by RickCogley** [comment]
Hi @anthonyfok, is this ok: 

jrc screenshot 2016-02-06 at 7 41 14 am

**Comment by anthonyfok** [comment]
Many thanks, @RickCogley!  Yes, this new 800×600 image that you provided will do, though I did have to both resize and crop to make this 4:3 image fit the 600×400 (3:2) requirement.  :wink:

I also converted your image to a JPEG file using ImageMagick's `convert` with `-quality 95` to make it load faster (JPEG works much better than 256-color indexed PNG for the blue-green(?) gradient that you have) with the side benefit that your image is now updated on http://gohugo.io/showcase/ without bothering @spf13 to flush the cache.  :wink:

Committed as ed23711 (master) and f0f8297 (v0.15.docs).

**Comment by RickCogley** [comment]
Yikes, sorry for the trouble. I thought I got it right, but that's what I get working too early in the AM! 
Thanks!

--
Rick Cogley 
Mobile: 090-9959-5452 (Outside Japan, remove "0". +81-90-...)

> On Feb 6, 2016, at 6:41 PM, Anthony Fok <notifications@github.com> wrote:
> 
> Many thanks, @RickCogley <https://github.com/RickCogley>! Yes, this new 800×600 image that you provided will do, though I did have to both resize and crop to make this 4:3 image fit the 600×400 (3:2) requirement.  
> 
> I also converted your image to a JPEG file using ImageMagick's convert with -quality 95 to make it load faster (JPEG works much better than 256-color indexed PNG for the blue-green(?) gradient that you have) with the side benefit that your image is now updated on http://gohugo.io/showcase/ <http://gohugo.io/showcase/> without bothering @spf13 <https://github.com/spf13> to flush the cache.  
> 
> Committed as ed23711 <https://github.com/spf13/hugo/commit/ed23711e2ef1dbbc5decd45146151be6567466ca> (master) and f0f8297 <https://github.com/spf13/hugo/commit/f0f829730eb95e3fef72d23390be2af7e6c781fd> (v0.15.docs).
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/spf13/hugo/pull/1807#issuecomment-180726578>.
> 


-- 
*This email message and any attachments are confidential, and are meant to 
be read by the intended recipient only. If you are not the intended 
recipient, we would request you delete this message or any attachments 
without reading or distributing, and kindly advise eSolia Inc. (contacts: 
esolia.com/about <http://esolia.com/about>). Thank you in advance.*

**Pull request closed without merging**
