### PR TITLE
Added 'themes' as a default new site directory

### PR DESCRIPTION
**Pull request by inondle**
Pretty succinct pull request, added 'themes' directory to new site command so it is made by default.

### CODE REVIEW

**Comment by inondle** [comment]
Looking at the AppVeyor log output it seems to fail the `TestDoNewSite_error_force_dir_inside_exists` test. I re-ran `go test ./...` on my local machine and didn't get any errors for the `github.com/spf13/hugo/commands` section.

**Comment by anthonyfok** [comment]
Hi @inondle, thank you for your contribution.

The AppVeyor build failure does not seem to be related to your commit.

As a matter of fact, the AppVeyor build began failing in the master branch a couple of commits ago too, though it does not seem to be related to the recent commits either, as rebuild of 10 commits ago fail too.

I will see if I can install Go on my wife's computer and start testing.  ;-)

Merged as f6fdfcd (master).

**Comment by anthonyfok** [comment]
The recent `go test ./...` failure on AppVeyor (i.e. MS Windows build):

```
=== RUN   TestDoNewSite_error_force_dir_inside_exists
--- FAIL: TestDoNewSite_error_force_dir_inside_exists (0.00s)
	assertions.go:203:                         	Error Trace:	new_test.go:68
			Error:		Expected value not to be nil.
		
```

appears to be the result of commit spf13/afero@3a224e9: "Normalize Paths so "/boo/" and "/boo" are the same".  This only triggers the `go test` error on Windows though, and I was able to reproduce this same error on my wife's Windows 8.1 (amd64) machine.  I wonder why...

Cc: @spf13

**Comment by spf13** [comment]
I'm looking into it.

**Comment by anthonyfok** [comment]
Thanks for looking into it, @spf13.

I tried playing with it a little bit and posted what I learned here: https://github.com/spf13/afero/issues/26, though I must admit I know very little on how Go handles file/path names in Windows.

**Pull request closed without merging**
