### PR TITLE
Added ability to exec arbitrary commands from templates.

### PR DESCRIPTION
**Pull request by aliafshar**

### CODE REVIEW

**Comment by spf13** [comment]
I'm still worried about this. I'm punting on this until after the v0.13 release is out. I'm thinking more of having a few dedicated exec based functions... like "grep"... but then concerned about how it would work with systems like windows which don't have them available.

**Comment by yml** [comment]
@spf13 I understand the security concern but I think that a reasonable middleground would be to use a whitelist coming from the [datafiles](http://gohugo.io/extras/datafiles/) to restrict the binaries that can be called.

Does it sounds acceptable ?

**Comment by bep** [comment]
@yml the datafiles can also be set in themes. So any white list would have to live in global config.

**Comment by yml** [comment]
@bep good call. Would checking the `exec_whitelist` in the global config be enough to let this feature get in.

**Comment by moorereason** [comment]
Closing this PR as we won't be merging, as is.  Lacks safeguards.  The security issues needs more thought and discussion.

**Pull request closed without merging**
