### PR TITLE
Document getenv template function

### PR DESCRIPTION
**Pull request by mdhender**
Documents the `getenv` function added for #977.

References #977

### CODE REVIEW

**Comment by bep** [comment]
This doesn't merge cleanly re your sort PR.

**Comment by mdhender** [comment]
Do I close out this PR and open a new one when I deal with the merge conflicts?

**Comment by bep** [comment]
No, that just adds confusion.

Do a `rebase master` 
Resolve the conflicts (by fixing it manually, then do a git add .)
Then do a push -f

**Comment by bep** [comment]
I wrote some lines about the rebase master on the disuss forum a while ago.

**Comment by bep** [comment]
On a side note: I COULD have fixed this myself, but it is better long term for you and me that we all gets to be git Ninjas... :-)

**Comment by mdhender** [comment]
It will be a while before my license plate reads "ILUVGIT", but I'm getting there.

**Comment by bep** [comment]
Well, it's in my eyes one of the most impressive pieces of software around. But it takes some time to wrap the brain around it.

**Comment by mdhender** [comment]
It looks like it's merged and it looks like the PR picked that up automagically. There's three commits out on this branch. I don't think that I can squash them since I pushed to GitHub already.

**Comment by bep** [comment]
Yes, you can.

* You will have to squash those three commits into one (Google it)
* then do a force push (push -f) to this branch

**Comment by mdhender** [comment]
I think that is down to one commit message.

**Comment by bep** [comment]
This is 3 commits and I cannot cherry-pick this as is.

**Pull request closed without merging**
