### PR TITLE
Add new tutorial for multilingual sites

### PR DESCRIPTION
**Pull request by RickCogley**
Simple tutorial showing one pattern for creating a multilingual site in
Hugo.

### CODE REVIEW

**Comment by bep** [comment]
Merged and live soon. Sorry it took so long to merge ... I have had real life creeping in on me lately :-)

**Comment by RickCogley** [comment]
@bep awesome! "Real life"? What is this "real life"!? :-)

**Comment by nicolinuxfr** [comment]
So how should I add something about dates ? Clone everything, edit only this file and make a PR ?

**Comment by RickCogley** [comment]
Yeah, once the file's merged, clone your fork of spf13/hugo, make a branch, edit this file, commit and push the branch to your fork, and then make the PR. At least that is what I have done so far.

**Comment by bep** [comment]
Real lite eq lot og work

**Comment by bep** [comment]
Life

**Comment by bep** [comment]
Oh, and remind me not to type on the mobile. Real life = lots of real work, in contrast to this playground.

**Pull request closed without merging**
