### PR TITLE
Robots txt feature

### PR DESCRIPTION
**Pull request by ifraixedes**
This PR provides to hugo the possibility to generate a "robots.txt" file following their template mechanism.

The concept is to operate in the same way that "sitemap.xml" works.

### CODE REVIEW

**Comment by spf13** [comment]
Can you add some documentation for this in the docs?

**Comment by ifraixedes** [comment]
@spf13 I can; can you tell me where please?

**Comment by bep** [comment]
And also please squash the commits and have a look at the commit message guidelines.

**Comment by ifraixedes** [comment]
@bep I've read it but I wasn't sure if you want to do that right after it has been reviewed and before merging it.

For me it's clearer to see all the commits when I review code, but you may prefer to see only one commit,  which is fine, but I didn't want to do until somebody told me that because I can always squash them but not the opposite.

Please confirm me that you want that I squash them now.

**Comment by spf13** [comment]
I think the commit looks good. I would like to see it in a single commit to do a final review. Perhaps add a new docs page under extras.

**Comment by ifraixedes** [comment]
@spf13  OK, no problem with the single commit, thanks to confirm it to go ahead.
I'm going to rebase, squash and try to add something under extras

**Comment by ifraixedes** [comment]
I've written some documentation.
I realized that I had only added the feature to [commands/hugo](http://gohugo.io/commands/hugo/) when I thought that I had done in [overview/configuration](http://gohugo.io/overview/configuration/), so I added there and a content in extra as commented.

**Comment by bep** [comment]
Merged in 9a6dc6c

**Comment by anthonyfok** [comment]
> Merged in 9a6dc6c

Something happened after this commit:

```
$ hugo server -s docs
ERROR: 2016/01/06 17:19:49 site.go:795: Two or more menu items have the same name/identifier in Menu "main": "Table of Contents".
Rename or set an unique identifier.
```

Not sure what happened.  Investigating...

**Comment by anthonyfok** [comment]
Found the culprit.  Will commit a fix soon.

**Comment by anthonyfok** [comment]
The problem

```
$ hugo server -s docs
ERROR: 2016/01/06 17:19:49 site.go:795: Two or more menu items have the same name/identifier in Menu "main": "Table of Contents".
Rename or set an unique identifier.
```

has been fixed in commit 2c661674317d980fff4f48cb410b929fa18b0bf2.

**Comment by ifraixedes** [comment]
@anthonyfok my fault, I forgot to run `hugo` in docs and obviously I wrote the documentation in a bad time. My apologies for those.

**Comment by anthonyfok** [comment]
@ifraixedes No worries, this is just a trivial error that is easily fixed.  Thank you for writing this much needed feature and providing documentation for it!  Your contribution is very much appreciated.  :-)

**Pull request closed without merging**
