### PR TITLE
Fix golint warnings for helpers/general.go

### PR DESCRIPTION
**Pull request by LK4D4**
It includes go-style of avoinding elses on after return and fix of
comment for NormalizeHugoFlags.

### CODE REVIEW

**Comment by bep** [comment]
In this case we're gonna keep the if/elses (golint is suggestions). Could you trim down this pull request to the error in the comment?

**Comment by LK4D4** [comment]
@bep I wonder why you want to keep them?

**Comment by bep** [comment]
In normal cases, I agree that multiple returns are better than nested if/elses. I have ran golint on Hugo several times in the past, and have skipped these same warnings before:

1) These nested, almost switch-like if-elses reads nicely as-is. It is a matter of taste.
2) Changing them just because golint says so is not a good reason enough. There is plenty of stuff to do in Hugo with more substance.
3) If the original author of this code had opened up this pull request, I would have merged it.

**Comment by LK4D4** [comment]
@bep ok, your repo - your rules
even if I think that go-community style overpower any personal style. I think that it should be less place for personal styles.

**Comment by bep** [comment]
Actually it's @spf13 s repo. I totally obey with the go vet rules. But I think you will find lots of golint warnings even in Go's stdlib.

**Comment by bep** [comment]
Merged in 7b4e4769d070c3af97abaca9c1169f9e341be141

Thanks.

**Pull request closed without merging**
