### PR TITLE
hugo tutorial by Shekhar Gulati

### PR DESCRIPTION
**Pull request by shekhargulati**

### CODE REVIEW

**Comment by spf13** [comment]
@shekhargulati It would be amazing if this content could be repurposed for the Quickstart page. It's superior to what is currently there and it's one of our most trafficked pages. 

The page is at http://gohugo.io/overview/quickstart/ and the source is at https://github.com/spf13/hugo/edit/master/docs/content/overview/quickstart.md

This is independent of this Pull Request.

**Comment by bep** [comment]
That tutorial is ... fantastic! Really good.

**Comment by shekhargulati** [comment]
thanks @spf13 and @bep. I would love to contribute my tutorial to Hugo documentation. Can we credit me as author and point to the original source in the quickstart page?

**Comment by spf13** [comment]
I'm fine with that at the end of the document.

**Comment by shekhargulati** [comment]
@spf13 great I will send the PR after some cleanup.

**Comment by digitalcraftsman** [comment]
Hi @shekhargulati,

indeed a great tutorial. I've merged your reference in the press section as ac2eaca06dfd0c70c59d170aafbbebda2795a71f (master) and f71871e907163e57cd7ac13f62b917b24044f3fc (v0.15.docs).

**Pull request closed without merging**
