### PR TITLE
Html commented frontmatter

### LINKED ISSUE #1428: Support HTML comments frontmatter
Something like 
```
<!---TOML
+++
title = "spf13-vim 3.0 release and new website"
description = "spf13-vim is a cross platform distribution of vim plugins and resources for Vim."
tags = [ ".vimrc", "plugins", "spf13-vim", "vim" ]
date = "2012-04-06"
categories = [
  "Development",
  "VIM"
]
slug = "spf13-vim-3-0-release-and-new-website"
+++
-->
```

Or

```
<!--- title : "spf13-vim 3.0 release and new website" -->
<!--- description : "spf13-vim is a cross platform distribution of vim plugins and resources for Vim." -->
<!--- tags :  ".vimrc", "plugins", "spf13-vim", "vim" -->
<!--- date : "2012-04-06"-->
<!--- categories :"Development", "VIM" -->
<!--- slug : "spf13-vim-3-0-release-and-new-website"-->
```

This is very important when content is not processed by hugo and display elsewhere directly.The frontmatter is very noise.

### PR DESCRIPTION
**Pull request by SvenDowideit**
Closes  #1428

### CODE REVIEW

**Comment by ariejan** [comment]
Why does your commit contain Docker stuff?

**Comment by SvenDowideit** [comment]
@ariejan and woooosh, its gone :)

I do wonder if building with Docker would be welcome in a separate PR ...

**Comment by SvenDowideit** [comment]
@wenerme @bep @spf13

**Comment by bep** [comment]
Merged in a1e3243

For future reference, please end the commit body with "Fixes #<id>"; it saves me from doing it.

**Pull request closed without merging**
