### PR TITLE
Small Doc Changes

### PR DESCRIPTION
**Pull request by TheJawaEyes**

### CODE REVIEW

**Comment by anthonyfok** [comment]
Hello @TheJawaEyes,

Thank you for your contribution.  Would you mind signing the Contributor License Agreement (CLA) too?  Thanks!

**Comment by spf13** [comment]
For small typos the CLA does not need to be signed.

**Comment by anthonyfok** [comment]
Thank you @spf13 for the green light.  Will merge soon.

**Comment by anthonyfok** [comment]
Thank you @TheJawaEyes!  Your revision to the introduction paragraphs have been merged as 01c87d2 (master) and 57a5fde (v0.14.docs).

**Pull request closed without merging**
