### PR TITLE
docs: Add shapeshed.com to the showcase

### PR DESCRIPTION
**Pull request by shapeshed**
Adding shapeshed.com to the showcase sites

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @shapeshed,

thank you for adding your website to the showcase of Hugo. I've merged your contribution as  8a63ebc.
The website should be updated within the next minutes.

Cheers,
Digitalcraftsman

**Comment by shapeshed** [comment]
Thanks for this. This doesn't seem to show. I can also see that the codeking site isn't showing as referenced in this PR, although two other sites added recently do show.

https://github.com/spf13/hugo/pull/2539 

Can't see anything obvious in the metadata and is ok locally.

**Comment by digitalcraftsman** [comment]
My bad - I pushed the commits to the master branch, but I forgot to push them to the v0.17 branch as well. The last one will be used to build the Hugo website. Therefore, it worked locally (with master).

**Comment by shapeshed** [comment]
Ah good. Not a bug in my metadata.

Thank you for your work on hugo.

**Pull request closed without merging**
