### PR TITLE
Add GitHub style code fence support to mmark. Fixes #1258.

### LINKED ISSUE #1258: Add GitHub style code fence support to mmark
See #1255 

/cc @bramp

### PR DESCRIPTION
**Pull request by bramp**

### CODE REVIEW

**Comment by bramp** [comment]
Doh, for some reason the tests are failing. I will fix.

**Comment by SvenDowideit** [comment]
oh excellent - I didn't take mmark along for #1398 but I do want to see if what the difference between the 2 backends are :)

**Comment by bramp** [comment]
I personally don't use mmark, but I felt we should keep it at feature
parity. However, in #1398 I suggest you get blackFriday working before you
add mmark.

**Comment by bramp** [comment]
Fixed up the tests. This PR should be ready for review.

**Comment by bep** [comment]
The code looks good. But could you

1) Squash into one commit
2) Get the commit message in line with the contributor guide

**Comment by bep** [comment]
Bump.

**Comment by spf13** [comment]
Merged as c2c694f136ab285a077eeac32948ae9474badf47

**Pull request closed without merging**
