### PR TITLE
0.15 Docs: document Node.IsHome

### LINKED ISSUE #1672: Document Node.IsHome
`Node.IsHome` was added in v0.15 but is undocumented.

### PR DESCRIPTION
**Pull request by moorereason**
Closes #1672

### CODE REVIEW

**Comment by anthonyfok** [comment]
@moorereason, Thank you for your contributions!

I just wanted to say that you don't need to file separate pull requests for the `v0.15.docs` because @spf13 actually wrote a nifty script providing shortcuts (bash aliases) for "merging", or rather, "cherry-picking" pull requests.  That is done to avoid merge bubbles and to keep the Git history nice and linear.  :-)

One of which, called `prdocs`, cherry-pick pull requests into both `master` and `v0.15.docs` in one go.

So yes, usually one pull request against `master` is sufficient, unless you have some change that are only applicable to the `v0.15.docs` branch and not the `master` branch.

Thanks again!  :-)

**Comment by anthonyfok** [comment]
Merged as 377b394 (v0.15.docs); see Pull Request #1689.

**Comment by moorereason** [comment]
Thanks for the info, @anthonyfok.  I certainly don't mind doing less work!  :smile:

**Comment by anthonyfok** [comment]
:wink:

**Pull request closed without merging**
