### PR TITLE
Create mariosanchez.md

### PR DESCRIPTION
**Pull request by mariobox**
Submitting site for consideration in Hugo Showcase

### CODE REVIEW

**Comment by bep** [comment]
Can you also commit the thumbnail? Just push to the same branch.

**Comment by mariobox** [comment]
Done.
Thanks!
Mario

**Comment by bep** [comment]
I may be blind, but I do not see it. Have you pushed it?

**Comment by mariobox** [comment]
Sorry... I had pushed it but forgot to create the pull request. You should see it now.
Thx,
M.

**Comment by bep** [comment]
Merged and live soon.

**Pull request closed without merging**
