### PR TITLE
Add trim and replace template functions

### PR DESCRIPTION
**Pull request by tomhelmer**
When working with muut i needed something that could transform "/article/photoswipe-gallery-hugo/" to "article-photoswipe-gallery-hugo". I could have made a custom function doing exactly this, but I thinj it's better solved with two more generic function used together:

     {{ $muutname := trim ( replace .RelPermalink "/" "-" ) "-" }}

### CODE REVIEW

**Comment by bjornerik** [comment]
Eventually people will ask to use this with `template.HTML` and not strings only.

See Chomp for an example.

Could you also `go fmt`  the source.

Please amend the commit and do a push -f.

**Comment by tomhelmer** [comment]
Sure, I'm not sure what you mean with `template.HTML`, How would it it be used ?

When I look at chomp I figure the trim function would look like:

    func Trim(a interface{}, b interface{}) (string, error) {
    	a_str, err := cast.ToStringE(a)
    	if err != nil {
    		return "", err
    	}

    	b_str, err := cast.ToStringE(b)
    	if err != nil {
    		return "", err
    	}

      return strings.Trim(a_str, b_str), nil;
    }

**Comment by bjornerik** [comment]
Yes - you are correct. The thing is, in a template, you're never really sure what the type is (int, int32, int64, template.HTML (a strongly typed ... string), string ...) so the  interface{} is the best argument here. If you look at the implementation of cast.ToString you will understand.

The usage is as before, like you say in the documentation.

Great addon btw, I need these.

**Comment by bjornerik** [comment]
Merged.

**Pull request closed without merging**
