### PR TITLE
Sorts function names in template documentation

### LINKED ISSUE #981: Arrange function names in templates/functions.md
It would be easier to find functions in the docs if they were sorted alphabetically.

### PR DESCRIPTION
**Pull request by mdhender**
Fixes #981 by sorting the names in the document.

### CODE REVIEW

**Comment by quoha** [comment]
Do I need to do something about the merge conflicts?

**Comment by bep** [comment]
There is too many conflicts to merge this. The main problem is @anthonyfok's renaming (safeHtml > sateHTML etc.) in 0.14 ... Not sure how to handle this, maybe best to wait with the sorting.

**Comment by mdhender** [comment]
I'll update and resubmit.

**Comment by mdhender** [comment]
I couldn't figure out how to put the pull into this request, so I created a separate PR #1015. This one should be closed.

**Pull request closed without merging**
