### PR TITLE
Remove incorrect reference in docs to `list.html` in content type directories

### PR DESCRIPTION
**Pull request by robmuh**
[Discussed in forums](https://discuss.gohugo.io/t/possible-documentation-error/3009).

### CODE REVIEW

**Comment by moorereason** [comment]
@robmuh, did you mean to include the surge.sh commit in this PR?  My suggestion would be to use a separate branch for each PR.

**Comment by digitalcraftsman** [comment]
I already merged surge.sh in #1996.

**Comment by robmuh** [comment]
Sorry about that I thought I had pulled down the latest. I think it snuck in when I did the `git stash` on the other changes for the tutorial I want to submit later today. How would you like to proceed? I can redo it.

**Comment by moorereason** [comment]
Merged in 49b4f8e.  Thanks, @robmuh!

**Pull request closed without merging**
