### PR TITLE
Sorts function names in template documentation

### LINKED ISSUE #981: Arrange function names in templates/functions.md
It would be easier to find functions in the docs if they were sorted alphabetically.

### PR DESCRIPTION
**Pull request by mdhender**
Fixes #981 by sorting the names in the document.

### CODE REVIEW

**Comment by mdhender** [comment]
I don't understand why the AppVeyor build failed. Running `hugo server -w` in the docs directory with current build from spf13/master seems to work for me.

**Comment by bep** [comment]
It failed for a reason that's not longer there. Try to do a push -f to trigger a new build.

**Comment by mdhender** [comment]
Would I push to this same PR? Is this from deleting my branch? You can still cherry-pick it but the AppVeyor build can't? That's the same thing that closes out PRs when I delete branches from my repo after sending in the PR?

**Comment by bep** [comment]
* You push to a branch, not a PR.
* I guess you have to amend to your commit to create a new one (git commit --amend) and the do git -f push mdhender <mybranch>

But I see you have deleted the branch, so that's not possible.

**Comment by mdhender** [comment]
Rebuilt as PR #1041

**Pull request closed without merging**
