### PR TITLE
docs : Add Nutspubcrawl.com to the showcase

### PR DESCRIPTION
**Pull request by jeremielondon**
We try to develop it in hugo, great tool guys. We are happy to receive
feed backs if you see things we could improve.
Best.

### CODE REVIEW

**Comment by bep** [comment]
A fellow Norwegian I remotely know said once that "What I love about London is that there are so many pubs, it is impossible to get kicked out of all of them!"

**Comment by jeremielondon** [comment]
You guys are welcome anytime, i ll be your private guide

**Comment by digitalcraftsman** [comment]
Hello @jeremielondon 

that a nice website if you live or have a stay in London. I've merged your contribution as  adc0572d.
Hugo's showcase section should be updated within the next minutes.

Cheers,
Digitalcraftsman

**Comment by jeremielondon** [comment]
Thanks, We try to help expats and Hugo makes our job easier, I'm still learning it to make the most of it. Great tool.

**Pull request closed without merging**
