### PR TITLE
all: Add TOML support for language files

### LINKED ISSUE #2577: Add TOML support for language files
Doing this in YAML is frustration galore.

EDIT: https://github.com/nicksnyder/go-i18n

### LINKED ISSUE #3200: Integrate the flatter and simpler lang file structure
See https://github.com/nicksnyder/go-i18n/issues/62

### PR DESCRIPTION
**Pull request by bogem**
Fixes #2577 
Fixes #3200

### CODE REVIEW

**Comment by bogem** [comment]
I will try to figure out tomorrow, why tests are broken.

**Comment by bogem** [comment]
Now it works

**Comment by bep** [comment]
It looks good, but I suspect you got it to go green by replacing a YAML test variant with the new TOML -- which doesn't really work; we have to support both, even if TOML is better.

This is the error I get when I build my site:

```
Started building sites ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15a8e24]

goroutine 1 [running]:
github.com/spf13/hugo/hugolib.(*Page).shouldBuild(0xc422586a00, 0x17a4470)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/page.go:781 +0x34
github.com/spf13/hugo/hugolib.(*Site).convertSource(0xc4200deb40, 0x178368c)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1237 +0x21a
github.com/spf13/hugo/hugolib.(*Site).createPages(0xc4200deb40, 0x17767e0, 0x9)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1258 +0xc1
github.com/spf13/hugo/hugolib.(*Site).process(0xc4200deb40, 0x101, 0xc420015db8, 0x9a10379202818a0, 0xed072ce2f)
```

**Comment by bogem** [comment]
It's very strange because it perfectly works with `examples/multilingual`. Something wrong with `p.s.Cfg.GetBool()` in this case. `p.s.Cfg` is not nil, but when you call `fmt.Println(p.s.Cfg)` you can see `en` and error on this line.

**Comment by bogem** [comment]
Is #3260 somehow related to this error?

**Comment by bep** [comment]
Doubt it. But I will fix that now and then I can check again.

**Comment by bogem** [comment]
The problem is what we can't see the errors, which go-i18n returns.
To reproduce you should write invalid translation file and you'll become the same error.

**Comment by bep** [comment]
I reverted that bad merge, and tested this PR with the new master applied, and still get an error.

Are you saying we are "swallowing" errors from go-i18n somewhere?

**Comment by bogem** [comment]
Yes

**Comment by bogem** [comment]
I figured out, where it is:
site.go:66 : applyDepsIfNeeded returns an error, but we doesn't use it:
```go
...
  applyDepsIfNeeded(cfg, sites...)

  h.Deps = sites[0].Deps

  return h, nil
}

func applyDepsIfNeeded(cfg deps.DepsCfg, sites ...*Site) error {
...
```

**Comment by bep** [comment]
OK, thanks, I will check.

**Comment by bogem** [comment]
I've already fixed it. I will push it in 5 minutes

**Comment by bep** [comment]
But even if I now get better error message, it still is breaking from this PR:

```
Error: Error building site: Failed to load translations in file "en.yaml": failed to unmarshal en.yaml: yaml: unmarshal errors:
  line 2: cannot unmarshal !!seq into map[string]map[string]interface {}
```

If I use `go-i18n` from master, all works fine.

**Comment by bep** [comment]
Failing YAML:

https://github.com/bep/bepsays.com/blob/master/i18n/en.yaml

**Comment by bogem** [comment]
It's because you have blank line at the beginning of your file.  If you delete it, everything will operate normally.
It's a bug of go-i18n, I will make a PR to fix it.

**Comment by bogem** [comment]
https://github.com/nicksnyder/go-i18n/pull/67

**Comment by bogem** [comment]
Now everything is fixed.

**Comment by bep** [comment]
Yes, now it works correctly on my site, too.

This is just great, you showed some real persistence landing this. This is a way more important feature than most people will appreciate -- until they start to use it in real projects of some size!

/cc @spf13 @rdwatters @budparr

**Comment by bogem** [comment]
Thank you, @bep 😌
But actually it can't be compared to all the work you do. Thank you for supporting this exciting project. I will contribute further to hugo and other side projects to make it better

**Comment by Mawulijo** [comment]
Very glad i am embrassing hugo. I have no idea what was going on but i knew i am in good company.

**Pull request merged**
