### PR TITLE
Multi-Lingual Authors

### PR DESCRIPTION
**Pull request by derekperkins**
@digitalcraftsman, is this ballpark what you're looking at for #2467?

Obviously the accessors would need be be altered to allow for overrides, so all the struct fields would have to be unexported and then turned into functions. Is there a `Node` language to use?

### CODE REVIEW

**Comment by derekperkins** [comment]
@bep Even if you don't want to tackle the multi-lingual piece of this now, I think that we should use functions instead of fields for the 0.17 release, and I also realized that I wasn't mapping weight in, so that has to get merged before release.

**Comment by bep** [comment]
This all tells me we also needs some tests for all of this.

**Comment by bep** [comment]
Also, functions just for the sake of a function just adds lines of code. If we add some side effects to these fields later, we can replace the field(s) with functions without the clients knowing it.

My main point being: Solving a concrete problem by also solving a set of non-problems is suboptimal.

**Comment by derekperkins** [comment]
Ok, now they aren't functions just for the sake of functions. I'm just trying to understand if this is the right direction to take this PR for multi-lingual author support.

**Comment by digitalcraftsman** [comment]
Maybe @ bep has a better approach to tackle this problem. The current approach requires that we have to pass the current language as argument to the accessors. Couldn't we instead read the current language from viper?

**Comment by derekperkins** [comment]
@digitalcraftsman I closed this in favor of #1850, where `Author` and `Authors` always return localized data, without having to provide a language parameter.

**Pull request closed without merging**
