### PR TITLE
examples: Update multilingual example

### LINKED ISSUE #2417: Update multilingual example
The current [multilingual](https://github.com/spf13/hugo/tree/master/examples/multilingual) example used workarounds to create an internationalized website. But since Hugo has [native i18n](https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md) support (as part of Hugo v0.17) it would be consquently to update the example as well.

### PR DESCRIPTION
**Pull request by bogem**
Use new i18n concept

Fixes #2417

Earlier the newlines were dos formatted. My text editor automatically translated them into unix format. That's why the whole files were changed.

### CODE REVIEW

**Comment by moorereason** [comment]
Fix the line endings for `examples/multilingual/static/main.css` while you're here.

**Comment by bogem** [comment]
@moorereason done

**Comment by moorereason** [comment]
LGTM :+1:

**Comment by digitalcraftsman** [comment]
Merged as 68ebf61.

**Pull request closed without merging**
