### PR TITLE
Insert code tag for server-side syntax highlighting

### LINKED ISSUE #1490: Include code tag for server-side syntax highlighting
GitHub-style code fencing as well as tildes output [a code tag for client-side highlighters](https://gohugo.io/extras/highlighting/#using-client-side-highlighting).

```html
<code class="language-go">
```

But the `{{< highlight >}}` short-code and PygmentsCodeFences options (#1255) don't include the code tag.

I am porting a Jekyll+Pygments site to Hugo where I use the code tag for CSS hooks, including displaying the language of the snippet. With Jekyll the output looks like this:

```html
<code class="language-go" data-lang="go">
```

### PR DESCRIPTION
**Pull request by nathany**
Inserts a code tag into Pygments output with the language-info that is present when using client-side highlighting (useful for CSS hooks)

```html
<code class="language-go" data-lang="go">
```

closes #1490

This change won't show up until the Pygments cache is cleared:

```console
rm -Rf $TMPDIR/hugo_cache
```

or ` --ignoreCache`

### CODE REVIEW

**Comment by nathany** [comment]
CircleCI is down right now :frowning: http://status.circleci.com/incidents/8rklh3qqckp1

**Comment by nathany** [comment]
CircleCI is back up. Can somebody hit "Rebuild" please?

**Comment by bep** [comment]
No need. Merged. This will be useful to me, too.

**Comment by nathany** [comment]
Thanks Bjørn.

**Pull request closed without merging**
