### PR TITLE
docs: Add lucumt.info to showcase

### PR DESCRIPTION
**Pull request by lucumt**
Add a new hugo website example to hugo,the address is http://lucumt.info , and is suitable for the Chinese users.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @lucumt,

thank you submitting the addition of your website to the showcase. Before we can merge it please make sure to sign the CLA that's linked in the comment above.

**Comment by lucumt** [comment]
@digitalcraftsman  thank you for your kinder remind,but I have signed the CLA yesterday and it said "You have signed the CLA for spf13/hugo",now I just sign the CLA in another computer,and it also said "You have signed the CLA for spf13/hugo",but the check result still shows that I do not sign the CLA,I do not know why,can you helo me,please?

**Comment by lucumt** [comment]
@digitalcraftsman  all checks have passed now!

**Comment by digitalcraftsman** [comment]
I've merged your addition as 431d5974.

**Pull request closed without merging**
