### PR TITLE
Add tests for embedded shortcodes

### LINKED ISSUE #1956: tpl: Write tests for embedded shortcodes
These will never show up in code coverage reports, but we need to write tests for the embedded shortcodes.

Shortcodes are in `tpl/template_embedded.go`.

### PR DESCRIPTION
**Pull request by ks888**
Fixes #1956

### CODE REVIEW

**Comment by ks888** [comment]
The builds fail due to cyclic import. The new test in tpl imports hugolib, and hugolib imports tpl.

I guess I need to find ways to test embedded shortcodes without importing hugolib.

**Comment by bep** [comment]
I think the pragmatic thing to do here is to move that test file to /hugolib.

**Comment by ks888** [comment]
Certainly moving the test file is simpler way. I will try.

**Comment by ks888** [comment]
I fixed the problem and the build is successful now. Please take a look.

**Comment by bep** [comment]
Very good!

**Comment by ks888** [comment]
Sorry this merged PR breaks AppVeyor build. I created the new PR #2225 to fix this issue.

**Pull request closed without merging**
