### PR TITLE
Extend the built-in shortcodes

### PR DESCRIPTION
**Pull request by digitalcraftsman**
See #1576.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Should I squash everything into a single commit?

**Comment by bep** [comment]
No. These are fine as separate commits.

**Comment by digitalcraftsman** [comment]
I've merge them as part of Hugo v0.15 I could also update the release notes.

**Comment by moorereason** [comment]
I've looked at the `youtube` shortcode, and I'm not a big fan of it.  `style` tags?  Shame.

I'm working on an enhancement.

**Comment by moorereason** [comment]
I've submitted PR #1597 to add a shortcode `.ParamsType` function.  With that commit, I would propose updating these defaults to be more concise and flexible.  Here's how I would define the Youtube shortcode (line breaks for readability):

```django
{{ if eq .ParamsType "position" }}
<div class="{{ if len .Params | eq 2 }}{{ .Get 1 }}{{ else }}youtube-container{{ end }}">
  <iframe src="https://www.youtube.com/embed/{{ .Get 0 }}" allowfullscreen frameborder="0"></iframe>
 </div>
{{ else }}
<div class="{{ if .Get "class" }}{{ .Get "class" }}{{ else }}youtube-container{{ end }}">
  <iframe src="https://www.youtube.com/embed/{{ .Get "id" }}" allowfullscreen frameborder="0"></iframe>
 </div>
{{ end }}
```

Example references:
```
{{< youtube f8TkUMJtK5k >}}
{{< youtube f8TkUMJtK5k flex-video >}}
{{< youtube id="f8TkUMJtK5k" class="flex-video" }}
```

I like this approach because the user can control everything via SASS/CSS:

```sass
.flex-video {
  width: 560px;
  height: 315px;

  iframe {
    width: 100%;
    height: 100%;
  }
}
```

**Comment by bep** [comment]
I had a look at this, too -- and having only inline style tags is not ideal. But it is the only way for a shortcode like this to be truly standalone.

But they should be fallback options, somehow.

**Comment by digitalcraftsman** [comment]
@moorereason I know that inline style tags are an ugly way to add CSS code. But this is the only (as far as I know) for a shortcode to stay independent and to work out of the box. It was my intention that they take the full width of the layout and are responsive. With defaults, the user doesn't need to add any styling to achieve this.

I like your approach to give users more flexibility to style the elements of the shortcode.

**Comment by moorereason** [comment]
I've updated PR #1597 to use a simple boolean, as @bep suggested.  Since it doesn't sound like I'm going to win the style argument, here's an updated example:

```django
{{ if .IsNamedParams }}
<div {{ if .Get "class" }}class="{{ .Get "class" }}"{{ else }}style="position: relative; padding-bottom: 56.25%; padding-top: 30px; height: 0; overflow: hidden;"{{ end }}>
  <iframe src="https://www.youtube.com/embed/{{ .Get "id" }}" {{ if not (.Get "class") }}style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" {{ end }}allowfullscreen frameborder="0"></iframe>
 </div>
{{ else }}
<div {{ if len .Params | eq 2 }}class="{{ .Get 1 }}"{{ else }}style="position: relative; padding-bottom: 56.25%; padding-top: 30px; height: 0; overflow: hidden;"{{ end }}>
  <iframe src="https://www.youtube.com/embed/{{ .Get 0 }}" {{ if len .Params | eq 1 }}style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" {{ end }}allowfullscreen frameborder="0"></iframe>
 </div>
{{ end }}
```
If you pass in a class name, we use that instead of the built-in style tags.  The logic on the `iframe` is that if you pass in a `class`, it's only for the out `div` container, and I assume that if you're using CSS classes, then you know how to select the `iframe` inside your container `div`.

**Comment by bep** [comment]
That I like.

**Comment by digitalcraftsman** [comment]
I've added the `IsNamedParams` property from @moorereason (see #1597) in the shortcodes.

**Comment by bep** [comment]
Looks good to me. Any comments @moorereason ?

**Comment by moorereason** [comment]
Does it matter we use `src="//hostname/..."` on some links and `src="https://hostname/..."` on others.  Why not remove the protocol from all links?  Isn't that the *proper* way to include remote resources?

On the twitter shortcode, I'd just send the tweet ID.  The username is unnecessary:

```
http://api.twitter.com/1/statuses/oembed.json?id={{ index .Params 0 }}
```

**Comment by digitalcraftsman** [comment]
I've made every shortcode protocol independent by just leaving the `//`, except in the Twitter shortcode. This shortcode make use of `getJSON`. Without adding a specific protocol the function isn't able to request the data since an error message is returned: `unsupported protocol scheme ""`.

Now, the Twitter shortcode just requires the tweet's id.

**Comment by moorereason** [comment]
LGTM :+1: 

PS - @digitalcraftsman, I think you need to sign the new CLA.  Hugo is now Apache 2.0 licensed!  Yea!

**Comment by digitalcraftsman** [comment]
Done!

Nice to see that @spf13 was finally able to make transition.

**Comment by bep** [comment]
As it is "years between Hugo releasees", we might take this discussion, too:

I notice you use the `GetJSON` to pull in tweets at build time. I guess this will load faster than using the embedded version?

```
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/reneefrench">@reneefrench</a> found the original design by me and sketch by Renee for <a href="https://t.co/1PR6bX5cDd">https://t.co/1PR6bX5cDd</a> <a href="https://twitter.com/hashtag/golang?src=hash">#golang</a> <a href="https://t.co/qrVN7we8dP">pic.twitter.com/qrVN7we8dP</a></p>&mdash; Rob Pike (@rob_pike) <a href="https://twitter.com/rob_pike/status/667781817756356613">November 20, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by bep** [comment]
Good work. Merged in 311307c

**Pull request closed without merging**
