### PR TITLE
Second fix for Amber templates

### PR DESCRIPTION
**Pull request by scottcwilson**
As discussed in https://github.com/spf13/hugo/commit/e3ea4b48a274770d8a45fe7c1dbbce2340ec4e2d

### CODE REVIEW

**Comment by bep** [comment]
Please provide a proper commit message. This one may look sensible now, but will contain no information after the next 10 Amber fixes.

**Comment by bep** [comment]
And could you remove the unrelated changes?

**Comment by scottcwilson** [comment]
sorry!  Not sure how my Amber work got in there.  Hopefully this one is good.

**Comment by bep** [comment]
Merged in 8a48412

**Pull request closed without merging**
