### PR TITLE
Add md5 and sha1 template functions

### LINKED ISSUE #1910: Add hash template functions
It will be nice to have ability to hash content on template.

Two possibilities:

1. A generic hash function `{{ hash <CONTENT> <ALGORITHM> }}`
2. Common algorithm hash function pipeline `{{ .Site.Params.my_var | md5 }}`

Good candidates should be:

- `md5` 
- `sha1`
- `sha2`

--- 

*Use case*: generate *Gravatar* url from `email`

```
<meta property="og:image" content="http://www.gravatar.com/avatar/{{ .Site.Params.gravatar.email | md5 }}">
<meta property="og:image" content="http://www.gravatar.com/avatar/{{ hash .Site.Params.gravatar.email "md5" }}">
```

### PR DESCRIPTION
**Pull request by digitalcraftsman**
Fixes #1910.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
@bep since the template functions' name would conflict with the corresponding package names I added an `_` as [prefix](https://github.com/digitalcraftsman/hugo/blob/tplfuncs/hashing/tpl/template_funcs.go#L18-L19). Let me know if you're not happy with the way how the conflict is handled.

**Comment by bep** [comment]
>an _ as prefix. 

That's fine. But you might add the error case to the tests (see the expect false interface{} construct used elsewhere).

Also add the two functions to the "smoke test at the top of the file".

**Comment by digitalcraftsman** [comment]
I updated the test file accordingly.

**Comment by bep** [comment]
Merged in 94c3825

**Comment by digitalcraftsman** [comment]
Thanks.

**Pull request closed without merging**
