### PR TITLE
tpl: Extend where to iterate over maps

### PR DESCRIPTION
**Pull request by moorereason**
Refactor and extend where to iterate over maps.

### CODE REVIEW

**Comment by moorereason** [comment]
@bep, can you test this PR out?  It needs to be extended to cover more cases, but I'm stuck.

I've added a test case that I believe matches a data structure from `.Site.Data`.  My results are exactly the same (print `%#v` in the test case to see it), but `DeepEquals` returns false.  I can't figure out what I'm missing here.  Need another set of eyes on it.  Thanks

**Comment by bep** [comment]
Change the check in the test to:

```go
if !reflect.DeepEqual(results, this.expect) {
				t.Errorf("[%d] Where clause matching %v with %#v, got\n%#v but expected\n%v", i, this.key, this.match, results, this.expect)
			}
```

And it will be more visible.

**Comment by bep** [comment]
They look the same to me, too .. Which, I guess, must mean they are different in the types they contain (int vs int64?)

**Comment by moorereason** [comment]
Found it.  I was returning `rv` (reflect.Value) instead of `rv.Interface()` (a map).

**Comment by bep** [comment]
@moorereason could you do a rebase of this one against master?

**Comment by moorereason** [comment]
@bep, done.

**Pull request merged**
