### PR TITLE
Improve documentation for menu rendering.

### LINKED ISSUE #1393: Fix menu doc
```
Additionally, there are some relevant functions available on the page:
IsMenuCurrent (menu string, menuEntry *MenuEntry ) bool
HasMenuCurrent (menu string, menuEntry *MenuEntry) bool
```

Also on node.

See

http://discuss.gohugo.io/t/confusion-regarding-proper-use-of-menus/1647/2

### PR DESCRIPTION
**Pull request by LiaungYip**
Fixes #1393

### CODE REVIEW

**Comment by LiaungYip** [comment]
Hopefully the examples I added will help new users trying to build nested menu templates.

I tried to cover the things which confused me when I was learning it:

* Using the `HasMenuCurrent()` and `IsMenuCurrent()` functions to style the active menu items;
* Using recursive partial templates to render nested menus;
* Only rendering the sub-menus relevant to the current page.

Note: I tried to sign the project CLA, but https://cla-assistant.io/spf13/hugo currently gives an error.

**Comment by LiaungYip** [comment]
[menutest.zip](https://github.com/spf13/hugo/files/785239/menutest.zip)

A small Hugo site illustrating use of the menu functions, on nested menus.

**Comment by bep** [comment]
This is very, very good.

A little note about the recursive part. I just fixed a recursive bug reported by a user that used inline template definitions to recursive render a menu, see the link from the issue linked in here:

https://github.com/spf13/hugo/commit/bdc02edfa8fb3178808420f529599e5970012304

**Comment by LiaungYip** [comment]
Hi @bep , is this good to merge or did you want further edits?

**Comment by bep** [comment]
No, it looks very good to me -- but I try to delegate doc merges to @digitalcraftsman

**Pull request merged**
