### PR TITLE
Go template primer - add index

### PR DESCRIPTION
**Pull request by RickCogley**
Related to @bjornerik 's answer in this discussion: http://discuss.gohugo.io/t/inserting-data-from-data-file-into-content-file-newbie-question/1002/3 ... I figured I'd make myself useful and add the reference to the index function, on the go template primer page. 

Also, I moved the reference links to the bottom. 

A general comment: as good as these docs are, the primer at this point makes some assumptions about audience knowledge, so some might find it lacking. Once I understand better, I might make some more clarifying edits.

### CODE REVIEW

**Comment by RickCogley** [comment]
Sorry I am not good at git. I intended to make a PR just for the last commit, because you had already merged my previous ones. This PR has three commits, though, and I don't understand why. Please advise if there is something I should do differently. For instance, is it better to make a new branch for every edit session?

**Comment by bep** [comment]
It is best to create a new branch per edit session. Branches are cheap.

In this case just leave it be -- I can squash them together.

**Comment by RickCogley** [comment]
Thanks @bep. That's what I'll do then!

**Comment by bep** [comment]
Merged and live soone.

**Pull request closed without merging**
