### PR TITLE
add snapcraft.yaml file

### PR DESCRIPTION
**Pull request by dholbach**
In the last days I created a snap of `hugo` and this PR contains the `snapcraft.yaml` that's required to build it. I tested it to some degree, but to make sure it's working well enough to be published and distributed to users I need your help.

I'd love to hear if you are generally interested in your software being available as a snap and if you could imagine shipping the `snapcraft.yaml` file in your source repository for easier publishing.

### Background info
If you haven't heard of snaps yet, they are self-contained apps, which can be used on a [multitude of Linux systems](https://snapcraft.io). Via `seccomp`, `apparmor` and other Linux security features, they provide great security for users, uploads to the store are available within seconds and you have
full control over your relevant stack.

Snaps can be installed by millions of users: Ubuntu 16.04 LTS and later have `snapd` installed by default and many other Linux distributions, like Arch, Debian, Gentoo, Fedora, openSUSE, OpenEmbedded, Yocto and OpenWRT made `snapd` (which powers the snap experience) available as well.

### Publishing
Uploading to the store can be done via the command line and there are multiple release channels available, so users can choose between for example stable, beta and alpha releases. You could even hook up `snapcraft upload` with Travis to auto-publish release tags or nightly builds. The process for this is very simple:

 - Once:
  - Register an account at http://myapps.developer.ubuntu.com/
  - Run `snapcraft login`
  - Run `snapcraft register hugo`
 - `snapcraft push hugo_<version>.snap --release=beta`

### CODE REVIEW

**Comment by bep** [comment]
Looks solid to me. 

What do you thing, @anthonyfok ?

**Comment by anthonyfok** [comment]
> What do you thing, @anthonyfok ?

Thanks for the heads up, @bep!  This is really awesome, especially it is contributed by *the* Daniel Holbach of Canonical (who makes Ubuntu).

I recall giving a talk at the Beijing Linux User Group maybe 8 years ago during which I played Daniel's video tutorial on Debian packaging and then gave further demonstrations.  (So yes, it was actually more like Daniel giving the talk, hehe...)

So yes, definitely, this is a very welcomed addition to Hugo, and will make Hugo readily available for more people in more places!  Thank you very much @dholbach!

**Comment by anthonyfok** [comment]
Merged as 44bf76d.  Thanks again Daniel!

**Comment by dholbach** [comment]
Thank YOU! :smiley:

**Comment by dholbach** [comment]
If you need any help publishing hugo to the store or anything, just let me know. :)

**Pull request closed without merging**
