### PR TITLE
Docs: add panel showing the last revision of a page

### PR DESCRIPTION
**Pull request by digitalcraftsman**
The panel also contains the version of the
documentation.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
As proposed in [this forum thread](https://discuss.gohugo.io/t/roadmap-to-hugo-v1-0/2278). I've taken the design of the panel that is shown at the bottom of the of https://themes.gohugo.io.

In one of the last pull requests @anthonyfok improved the contrast of the text. He noted:

> (Note: The changes are not immediately visible because CloudFlare (?) caches the CSS files...)

This could break some parts of the design since the HTML shows up but the stylesheets will not be updated immediately.

**Comment by anthonyfok** [comment]
> This could break some parts of the design since the HTML shows up but the stylesheets will not be updated immediately.

Hi @spf13, I think I should let you handle this pull request because committing this change will likely require an almost immediate purge of the CloudFlare cache on docs/static/css/bootstrap-theme.css
and docs/static/css/style.css.

And while you are at it, please upgrade Hugo 0.15-DEV for rendering gohugo.io to either 0.15 or 0.16-DEV.  Many thanks!

**Comment by spf13** [comment]
@anthonyfok I tried merging this in today. There's some conflicts with the CSS and I'm not sure how best to resolve it. Can you handle the merge and we can coordinate so I can clear the cache at the same time?

**Comment by digitalcraftsman** [comment]
The CSS filenames changed due to commit 883431442d07050c8ba4a69b536a2a7ef32b6e53 and f6f0111db622a5c7ea7ea342384dd3dda201e478. The updated commit merged the changes into the new CSS file.

**Comment by anthonyfok** [comment]
> Can you handle the merge and we can coordinate so I can clear the cache at the same time?

Hi @spf13, thanks for the note!  Sorry, I wasn't at the computer and missed you earlier today.

> The CSS filenames changed due to commit 8834314 and f6f0111. The updated commit merged the changes into the new CSS file.

Oops, I almost forgot about that renaming that I did!  Sorry for causing trouble, but thank you for your updated commit.  But... did you `git push -f` it to your `lastupdate` branch on GitHub?

**Comment by anthonyfok** [comment]
@spf13 wrote:
> Can you handle the merge and we can coordinate so I can clear the cache at the same time?

Hi @spf13, thanks for the note!  Sorry, I wasn't at the computer and missed you earlier today.  I will try to get on Gitter tomorrow so we can decide a time to merge and clear-the-cache at the same time, though it seems @digitalcraftsman has already resolved the conflict?

@digitalcraftsman wrote:
> The CSS filenames changed due to commit 8834314 and f6f0111. The updated commit merged the changes into the new CSS file.

Hi @digitalcraftsman, I almost forgot about that renaming that I did!  Sorry for causing trouble, but thank you for your updated commit.  But... did you `git push -f` it to your `lastupdate` branch on GitHub?  ;-)

**Comment by digitalcraftsman** [comment]
Hello @anthonyfok,

my mistake was that I created a branch in my fork and accidently another one in this repo called lastupdate. This happened by pushing once to the wrong remote repository.

However, both branches should be up to date.

**Comment by spf13** [comment]
So I've been able to merge this cleanly in and it looks good. Unfortunately most of the files don't have modtime in the front matter and so many are defaulting to the date they were initially created due to https://github.com/spf13/hugo/blob/master/hugolib/page.go#L625

I don't know if it's very useful if it's displaying largely quite incorrect information.

**Comment by bep** [comment]
See 01f71ba

This PR, however, makes the menu "stop working" (it doesn't expand), so I left it open.

**Comment by spf13** [comment]
I merged it and found that the menu worked just fine. I tried it in a few browsers with the same positive outcome. @bep, can you confirm/provide more information about what browser?

@anthonyfok @digitalcraftsman can you guys try it out?

I'm ready to push it when I get the go ahead.

**Comment by bep** [comment]
Confirm that this breaks menu on latest OS X on both Firefox and Chrome. I do notice some changes/additions in the JS section suspect doesn't belong here ... @digitalcraftsman

**Comment by anthonyfok** [comment]
I see the problem now.... jQuery 2.1.1 has been updated to jQuery 2.1.4, but the PR still refers to the old file, which means no jQuery is loaded, which would likely make the menu not work.

Maybe I will just merge it a bit later; looks like it should be harmless even if style.css isn't updated immediately, just that the new panel won't be stylized.

**Comment by anthonyfok** [comment]
Merged as b47652f (master) and 444624a (v0.15.docs).  Thank you for your contribution @digitalcraftsman!  The new "panel" footer looks really nice!

@spf13, when you are free, please clear the cache.  :-)  (Sorry for my paranoia earlier... looks like @digitalcraftsman contribution looks okay even without the proper CSS in place, hehe.  In retrospect, I should have just gone ahead and merged it 19 days ago.  :blush:)

**Comment by spf13** [comment]
That's why I didn't see anything wrong. I manually merged it in and made
sure to include the later jQuery.

**Comment by digitalcraftsman** [comment]
@anthonyfok said:
> I see the problem now.... jQuery 2.1.1 has been updated to jQuery 2.1.4, but the PR still refers to the old file, which means no jQuery is loaded, which would likely make the menu not work.

This is correct. @anthonyfok renamed some stylesheets and upgraded the version of jQuery. However, I resolved the name conflict with the stylesheets, but forget to update the inclusion of jQuery as well.
 ---

Thanks @bep for adding all missing last modification dates in the frontmatter.

**Pull request closed without merging**
